// BuddyLingo Spanish deck — per "Ultimate Vocabulary-Only Learning App" guide
// Entry: [english, spanish (nouns: with article), forms (plural / verb: yo-pres · pret · part · lexical prep), cat]
// Accents count as spelling; conocer/saber deliberately in different tiers.
window.TIER_NAMES = ["La Instrucción", "La Campaña"];
window.DECK = [
// ── Tier 1 · A1 (100) ──
["hello","hola","","B"],
["thank you","gracias","","B"],
["yes","sí","","B"],
["no","no","","B"],
["please","por favor","","B"],
["good","bueno","","A"],
["to be (essence)","ser","soy · fui · sido","V"],
["to have","tener","tengo · tuve · tenido","V"],
["and","y","","B"],
["to be (state)","estar","estoy · estuve · estado","V"],
["water","el agua","las aguas (f.)","N"],
["bread","el pan","los panes","N"],
["house","la casa","las casas","N"],
["man","el hombre","los hombres","N"],
["woman","la mujer","las mujeres","N"],
["child","el niño","los niños","N"],
["day","el día","los días","N"],
["night","la noche","las noches","N"],
["to go","ir","voy · fui · ido","V"],
["to come","venir","vengo · vine · venido","V"],
["to do / to make","hacer","hago · hice · hecho","V"],
["to say","decir","digo · dije · dicho","V"],
["big","grande","","A"],
["small","pequeño","","A"],
["new","nuevo","","A"],
["old","viejo","","A"],
["city","la ciudad","las ciudades","N"],
["railway station","la estación","las estaciones","N"],
["train","el tren","los trenes","N"],
["street","la calle","las calles","N"],
["time","el tiempo","los tiempos","N"],
["year","el año","los años","N"],
["to eat","comer","comí · comido","V"],
["to drink","beber","bebí · bebido","V"],
["to see","ver","veo · vi · visto","V"],
["to speak","hablar","hablé · hablado","V"],
["language","el idioma","los idiomas (m.)","N"],
["friend","el amigo","los amigos","N"],
["good morning","buenos días","","B"],
["good evening","buenas noches","","B"],
["goodbye","adiós","","B"],
["excuse me / sorry","perdón","","B"],
["how are you?","¿cómo estás?","","B"],
["money","el dinero","(sin plural)","N"],
["work","el trabajo","los trabajos","N"],
["to work","trabajar","trabajé · trabajado","V"],
["school","la escuela","las escuelas","N"],
["book","el libro","los libros","N"],
["to read","leer","leí · leído","V"],
["to write","escribir","escribí · escrito","V"],
["to buy","comprar","compré · comprado","V"],
["to get up","levantarse","me levanto · me levanté","V"],
["morning","la mañana","las mañanas","N"],
["evening","la tarde","las tardes","N"],
["week","la semana","las semanas","N"],
["month","el mes","los meses","N"],
["today","hoy","","A"],
["tomorrow","mañana","","A"],
["yesterday","ayer","","A"],
["here","aquí","","A"],
["there","allí","","A"],
["where?","¿dónde?","","B"],
["what?","¿qué?","","B"],
["who?","¿quién?","","B"],
["why?","¿por qué?","","B"],
["how?","¿cómo?","","B"],
["food","la comida","las comidas","N"],
["apple","la manzana","las manzanas","N"],
["milk","la leche","(sin plural)","N"],
["coffee","el café","los cafés","N"],
["beer","la cerveza","las cervezas","N"],
["table","la mesa","las mesas","N"],
["chair","la silla","las sillas","N"],
["door","la puerta","las puertas","N"],
["window","la ventana","las ventanas","N"],
["car","el coche","los coches","N"],
["to drive","conducir","conduzco · conduje · conducido","V"],
["to live (reside)","vivir","viví · vivido","V"],
["to love / to want","querer","quiero · quise · querido","V"],
["to need","necesitar","necesité · necesitado","V"],
["to give","dar","doy · di · dado","V"],
["to take","tomar","tomé · tomado","V"],
["to find","encontrar","encuentro · encontré · encontrado","V"],
["to know (a fact)","saber","sé · supe · sabido","V"],
["beautiful","bonito","","A"],
["bad","malo","","A"],
["fast","rápido","","A"],
["slow","lento","","A"],
["expensive","caro","","A"],
["cheap","barato","","A"],
["hot","caliente","","A"],
["cold","frío","","A"],
["right / correct","correcto","","A"],
["wrong","equivocado","","A"],
["family","la familia","las familias","N"],
["mother","la madre","las madres","N"],
["father","el padre","los padres","N"],
["dog","el perro","los perros","N"],
["to sleep","dormir","duermo · dormí · dormido","V"],
["to help","ayudar","ayudé · ayudado · ayudar a + inf.","V"],
// ── Tier 2 · A2 (100) ──
["brother","el hermano","los hermanos","N"],
["sister","la hermana","las hermanas","N"],
["cat","el gato","los gatos","N"],
["name","el nombre","los nombres","N"],
["number","el número","los números","N"],
["weather","el tiempo (clima)","(sin plural)","N"],
["rain","la lluvia","las lluvias","N"],
["sun","el sol","los soles","N"],
["to know (a person)","conocer","conozco · conocí · conocido","V"],
["to stay","quedarse","me quedo · me quedé","V"],
["to think","pensar","pienso · pensé · pensar en + algo","V"],
["to believe","creer","creí · creído","V"],
["to understand","entender","entiendo · entendí · entendido","V"],
["to answer","responder","respondí · respondido","V"],
["question","la pregunta","las preguntas","N"],
["answer","la respuesta","las respuestas","N"],
["to ask","preguntar","pregunté · preguntado","V"],
["to wait","esperar","esperé · esperado","V"],
["to begin","empezar","empiezo · empecé · empezar a + inf.","V"],
["to stop (doing)","dejar de","dejé · dejado · dejar de + inf.","V"],
["to arrive","llegar","llegué · llegado · llegar a","V"],
["to call (phone)","llamar","llamé · llamado","V"],
["airport","el aeropuerto","los aeropuertos","N"],
["main station","la estación central","las estaciones centrales","N"],
["world","el mundo","los mundos","N"],
["country","el país","los países","N"],
["trip / journey","el viaje","los viajes","N"],
["to travel","viajar","viajé · viajado","V"],
["ticket (travel)","el billete","los billetes","N"],
["bicycle","la bicicleta","las bicicletas","N"],
["driver","el conductor","los conductores","N"],
["departure","la salida","las salidas","N"],
["key","la llave","las llaves","N"],
["room","la habitación","las habitaciones","N"],
["kitchen","la cocina","las cocinas","N"],
["bathroom","el baño","los baños","N"],
["apartment","el piso","los pisos","N"],
["building","el edificio","los edificios","N"],
["to open","abrir","abrí · abierto","V"],
["to close","cerrar","cierro · cerré · cerrado","V"],
["to pay","pagar","pagué · pagado","V"],
["bill / check","la cuenta","las cuentas","N"],
["shop / store","la tienda","las tiendas","N"],
["bakery","la panadería","las panaderías","N"],
["meat","la carne","las carnes","N"],
["vegetables","la verdura","las verduras","N"],
["fruit","la fruta","las frutas","N"],
["cheese","el queso","los quesos","N"],
["egg","el huevo","los huevos","N"],
["butter","la mantequilla","(sin plural)","N"],
["sausage","la salchicha","las salchichas","N"],
["paella","la paella","las paellas","N"],
["potato","la patata","las patatas","N"],
["to cook","cocinar","cociné · cocinado","V"],
["delicious","delicioso","","A"],
["hungry","hambriento","tener hambre","A"],
["thirsty","sediento","tener sed","A"],
["tired","cansado","","A"],
["sick","enfermo","","A"],
["healthy","sano","","A"],
["doctor","el médico","los médicos","N"],
["hospital","el hospital","los hospitales","N"],
["pharmacy","la farmacia","las farmacias","N"],
["body","el cuerpo","los cuerpos","N"],
["head","la cabeza","las cabezas","N"],
["hand","la mano","las manos (f.)","N"],
["foot","el pie","los pies","N"],
["eye","el ojo","los ojos","N"],
["to hear","oír","oigo · oí · oído","V"],
["music","la música","(sin plural)","N"],
["to play","jugar","juego · jugué · jugar a + algo","V"],
["game","el juego","los juegos","N"],
["to win","ganar","gané · ganado","V"],
["to lose","perder","pierdo · perdí · perdido","V"],
["to run","correr","corrí · corrido","V"],
["to swim","nadar","nadé · nadado","V"],
["mountain","la montaña","las montañas","N"],
["sea","el mar","los mares","N"],
["forest","el bosque","los bosques","N"],
["tree","el árbol","los árboles","N"],
["flower","la flor","las flores","N"],
["bird","el pájaro","los pájaros","N"],
["to fly","volar","vuelo · volé · volado","V"],
["airplane","el avión","los aviones","N"],
["difficult","difícil","difíciles","A"],
["easy","fácil","fáciles","A"],
["important","importante","","A"],
["free","libre","","A"],
["always","siempre","","A"],
["never","nunca","","A"],
["often","a menudo","","A"],
["now","ahora","","A"],
["later","más tarde","","A"],
["to try","intentar","intenté · intentar + inf.","V"],
["to learn","aprender","aprendí · aprender a + inf.","V"],
["to forget","olvidar","olvidé · olvidarse de + algo","V"],
["to remember","acordarse","me acuerdo · me acordé · acordarse de + algo","V"],
["war","la guerra","las guerras","N"],
["word","la palabra","las palabras","N"],
["dictionary","el diccionario","los diccionarios","N"]
];
