// BuddyLingo German deck — built per "Ultimate German Vocabulary Module" (docs/german guide)
// Entry: [english, german lemma (nouns: with article), forms (nouns: plural · verbs: parts/government), cat]
// Rules honored: gender inherent (article shown from encounter 1), plural stored day one,
// separable verbs shown split, compounds after constituents, semantic neighbours interleaved.
window.TIER_NAMES = ["Grundausbildung", "Feldzug", "Heimatfront", "Vormarsch", "Versorgung", "Nachrichten", "Werkstatt", "Vorstoß", "Denkfabrik", "Feldherr"]; // 10 Bänder à 100 Lexeme
window.DECK = [
// ── Tier 1 · A1 · Grundausbildung (100) ──
["hello","hallo","","B"],
["thank you","danke","","B"],
["yes","ja","","B"],
["no","nein","","B"],
["please / you're welcome","bitte","","B"],
["good","gut","","A"],
["to be","sein","ist · war · ist gewesen","V"],
["to have","haben","hat · hatte · gehabt","V"],
["and","und","","B"],
["not","nicht","","B"],
["water","das Wasser","(no plural)","N"],
["bread","das Brot","die Brote","N"],
["house","das Haus","die Häuser","N"],
["man","der Mann","die Männer","N"],
["woman","die Frau","die Frauen","N"],
["child","das Kind","die Kinder","N"],
["day","der Tag","die Tage","N"],
["night","die Nacht","die Nächte","N"],
["to go","gehen","ging · ist gegangen","V"],
["to come","kommen","kam · ist gekommen","V"],
["to make / to do","machen","machte · gemacht","V"],
["to say","sagen","sagte · gesagt","V"],
["big","groß","","A"],
["small","klein","","A"],
["new","neu","","A"],
["old","alt","","A"],
["city","die Stadt","die Städte","N"],
["railway station","der Bahnhof","die Bahnhöfe","N"],
["train","der Zug","die Züge","N"],
["street","die Straße","die Straßen","N"],
["time","die Zeit","die Zeiten","N"],
["year","das Jahr","die Jahre","N"],
["to eat","essen","isst · aß · gegessen","V"],
["to drink","trinken","trank · getrunken","V"],
["to see","sehen","sieht · sah · gesehen","V"],
["to speak","sprechen","spricht · sprach · gesprochen","V"],
["language","die Sprache","die Sprachen","N"],
["friend","der Freund","die Freunde","N"],
["good morning","guten Morgen","","B"],
["good evening","guten Abend","","B"],
["goodbye","auf Wiedersehen","","B"],
["excuse me / sorry","Entschuldigung","","B"],
["how are you?","wie geht's?","","B"],
["money","das Geld","(no plural)","N"],
["work","die Arbeit","die Arbeiten","N"],
["to work","arbeiten","arbeitete · gearbeitet","V"],
["school","die Schule","die Schulen","N"],
["book","das Buch","die Bücher","N"],
["to read","lesen","liest · las · gelesen","V"],
["to write","schreiben","schrieb · geschrieben","V"],
["to buy","kaufen","kaufte · gekauft","V"],
["to get up","aufstehen","steht auf · stand auf · ist aufgestanden","V"],
["morning","der Morgen","die Morgen","N"],
["evening","der Abend","die Abende","N"],
["week","die Woche","die Wochen","N"],
["month","der Monat","die Monate","N"],
["today","heute","","A"],
["tomorrow","morgen","","A"],
["yesterday","gestern","","A"],
["here","hier","","A"],
["there","dort","","A"],
["where?","wo?","","B"],
["what?","was?","","B"],
["who?","wer?","","B"],
["why?","warum?","","B"],
["how?","wie?","","B"],
["food","das Essen","(no plural)","N"],
["apple","der Apfel","die Äpfel","N"],
["milk","die Milch","(no plural)","N"],
["coffee","der Kaffee","die Kaffees","N"],
["beer","das Bier","die Biere","N"],
["table","der Tisch","die Tische","N"],
["chair","der Stuhl","die Stühle","N"],
["door","die Tür","die Türen","N"],
["window","das Fenster","die Fenster","N"],
["car","das Auto","die Autos","N"],
["to drive / to ride","fahren","fährt · fuhr · ist gefahren","V"],
["to live (reside)","wohnen","wohnte · gewohnt","V"],
["to love","lieben","liebte · geliebt","V"],
["to need","brauchen","brauchte · gebraucht","V"],
["to give","geben","gibt · gab · gegeben","V"],
["to take","nehmen","nimmt · nahm · genommen","V"],
["to find","finden","fand · gefunden","V"],
["to know (a fact)","wissen","weiß · wusste · gewusst","V"],
["to know (a person)","kennen","kannte · gekannt","V"],
["beautiful","schön","","A"],
["bad","schlecht","","A"],
["fast","schnell","","A"],
["slow","langsam","","A"],
["expensive","teuer","","A"],
["cheap","billig","","A"],
["hot","heiß","","A"],
["cold","kalt","","A"],
["right / correct","richtig","","A"],
["wrong","falsch","","A"],
["family","die Familie","die Familien","N"],
["mother","die Mutter","die Mütter","N"],
["father","der Vater","die Väter","N"],
["dog","der Hund","die Hunde","N"],
["to sleep","schlafen","schläft · schlief · geschlafen","V"],
["to help","helfen","hilft · half · geholfen · jemandem (Dat.)","V"],
// ── Tier 2 · A2 · Feldzug (100) ──
["brother","der Bruder","die Brüder","N"],
["sister","die Schwester","die Schwestern","N"],
["cat","die Katze","die Katzen","N"],
["name","der Name","die Namen","N"],
["number","die Zahl","die Zahlen","N"],
["weather","das Wetter","(no plural)","N"],
["rain","der Regen","(no plural)","N"],
["sun","die Sonne","die Sonnen","N"],
["to become","werden","wird · wurde · ist geworden","V"],
["to stay","bleiben","blieb · ist geblieben","V"],
["to think","denken","dachte · gedacht","V"],
["to believe","glauben","glaubte · geglaubt","V"],
["to understand","verstehen","verstand · verstanden","V"],
["to answer","antworten","antwortete · geantwortet","V"],
["question","die Frage","die Fragen","N"],
["answer","die Antwort","die Antworten","N"],
["to ask","fragen","fragte · gefragt","V"],
["to wait","warten","wartete · gewartet · auf + Akk.","V"],
["to begin","anfangen","fängt an · fing an · angefangen","V"],
["to stop (doing)","aufhören","hörte auf · aufgehört · mit + Dat.","V"],
["to arrive","ankommen","kam an · ist angekommen","V"],
["to call (phone)","anrufen","rief an · angerufen","V"],
["airport","der Flughafen","die Flughäfen","N"],
["main station","der Hauptbahnhof","die Hauptbahnhöfe · Haupt + Bahnhof","N"],
["world","die Welt","die Welten","N"],
["country","das Land","die Länder","N"],
["trip / journey","die Reise","die Reisen","N"],
["to travel","reisen","reiste · ist gereist","V"],
["ticket (travel)","die Fahrkarte","die Fahrkarten · fahren + Karte","N"],
["bicycle","das Fahrrad","die Fahrräder · fahren + Rad","N"],
["driver","der Fahrer","die Fahrer · from fahren","N"],
["departure","die Abfahrt","die Abfahrten · from abfahren","N"],
["key","der Schlüssel","die Schlüssel","N"],
["room","das Zimmer","die Zimmer","N"],
["kitchen","die Küche","die Küchen","N"],
["bathroom","das Bad","die Bäder","N"],
["apartment","die Wohnung","die Wohnungen · from wohnen","N"],
["building","das Gebäude","die Gebäude","N"],
["to open","öffnen","öffnete · geöffnet","V"],
["to close","schließen","schloss · geschlossen","V"],
["to pay","bezahlen","bezahlte · bezahlt","V"],
["bill / invoice","die Rechnung","die Rechnungen","N"],
["shop / store","das Geschäft","die Geschäfte","N"],
["bakery","die Bäckerei","die Bäckereien","N"],
["meat","das Fleisch","(no plural)","N"],
["vegetables","das Gemüse","(no plural)","N"],
["fruit","das Obst","(no plural)","N"],
["cheese","der Käse","(no plural)","N"],
["egg","das Ei","die Eier","N"],
["butter","die Butter","(no plural)","N"],
["sausage","die Wurst","die Würste","N"],
["pretzel","die Brezel","die Brezeln","N"],
["potato","die Kartoffel","die Kartoffeln","N"],
["to cook","kochen","kochte · gekocht","V"],
["delicious","lecker","","A"],
["hungry","hungrig","","A"],
["thirsty","durstig","","A"],
["tired","müde","","A"],
["sick","krank","","A"],
["healthy","gesund","","A"],
["doctor","der Arzt","die Ärzte","N"],
["hospital","das Krankenhaus","die Krankenhäuser · krank + Haus","N"],
["pharmacy","die Apotheke","die Apotheken","N"],
["body","der Körper","die Körper","N"],
["head","der Kopf","die Köpfe","N"],
["hand","die Hand","die Hände","N"],
["foot","der Fuß","die Füße","N"],
["eye","das Auge","die Augen","N"],
["to hear","hören","hörte · gehört","V"],
["music","die Musik","(no plural)","N"],
["to play","spielen","spielte · gespielt","V"],
["game","das Spiel","die Spiele","N"],
["to win","gewinnen","gewann · gewonnen","V"],
["to lose","verlieren","verlor · verloren","V"],
["to run","laufen","läuft · lief · ist gelaufen","V"],
["to swim","schwimmen","schwamm · ist geschwommen","V"],
["mountain","der Berg","die Berge","N"],
["sea","das Meer","die Meere","N"],
["forest","der Wald","die Wälder","N"],
["tree","der Baum","die Bäume","N"],
["flower","die Blume","die Blumen","N"],
["bird","der Vogel","die Vögel","N"],
["to fly","fliegen","flog · ist geflogen","V"],
["airplane","das Flugzeug","die Flugzeuge · Flug + Zeug","N"],
["difficult / heavy","schwer","","A"],
["easy / light","leicht","","A"],
["important","wichtig","","A"],
["to forget","vergessen","vergisst · vergaß · vergessen","V"],
["to learn","lernen","lernte · gelernt","V"],
["free","frei","","A"],
["always","immer","","A"],
["victory","der Sieg","die Siege","N"],
["often","oft","","A"],
["dictionary","das Wörterbuch","die Wörterbücher · Wort + Buch","N"],
["now","jetzt","","A"],
["later","später","","A"],
["war","der Krieg","die Kriege","N"],
["word","das Wort","die Wörter","N"],
["to try","versuchen","versuchte · versucht","V"],
// ── Bands 3–6 · Heimatfront · Vormarsch · Versorgung · Nachrichten (append-only) ──
["parents","die Eltern","(nur Plural)","N"],["son","der Sohn","die Söhne","N"],["daughter","die Tochter","die Töchter","N"],
["grandmother","die Großmutter","die Großmütter · Groß + Mutter","N"],["grandfather","der Großvater","die Großväter · Groß + Vater","N"],["husband","der Ehemann","die Ehemänner","N"],
["wife","die Ehefrau","die Ehefrauen","N"],["friend (f)","die Freundin","die Freundinnen","N"],["neighbour","der Nachbar","die Nachbarn","N"],
["guest","der Gast","die Gäste","N"],["age","das Alter","(kein Plural)","N"],["birthday","der Geburtstag","die Geburtstage · Geburt + Tag","N"],
["person","die Person","die Personen","N"],["people","die Leute","(nur Plural)","N"],["boy","der Junge","die Jungen","N"],
["girl","das Mädchen","die Mädchen","N"],["baby","das Baby","die Babys","N"],["to be called","heißen","heißt · hieß · hat geheißen","V"],
["bedroom","das Schlafzimmer","die Schlafzimmer","N"],["storey / floor","das Stockwerk","die Stockwerke","N"],["wall","die Wand","die Wände","N"],
["roof","das Dach","die Dächer","N"],["garden","der Garten","die Gärten","N"],["bed","das Bett","die Betten","N"],
["lamp","die Lampe","die Lampen","N"],["to look for","suchen","suchte · hat gesucht","V"],["clock / watch","die Uhr","die Uhren","N"],
["hour","die Stunde","die Stunden","N"],["minute","die Minute","die Minuten","N"],["afternoon","der Nachmittag","die Nachmittage","N"],
["weekend","das Wochenende","die Wochenenden · Woche + Ende","N"],["moment","der Augenblick","die Augenblicke","N"],["early","früh","","A"],
["late","spät","","A"],["soon","bald","","B"],["still / yet","noch","","B"],
["already","schon","","B"],["never","nie","","B"],["sometimes","manchmal","","B"],
["to marry","heiraten","heiratete · hat geheiratet","V"],["young","jung","jünger · am jüngsten","A"],["married","verheiratet","","A"],
["alone","allein","","A"],["happy","glücklich","","A"],["sad","traurig","","A"],
["quiet","ruhig","","A"],["loud","laut","","A"],["clean","sauber","","A"],
["dirty","schmutzig","","A"],["own","eigen","","A"],["next","nächste","","A"],
["previous / last","letzte","","A"],["every","jeder","jede · jedes","B"],["both","beide","","B"],
["many","viele","","B"],["few","wenige","","B"],["whole","ganz","","A"],
["half","halb","","A"],["address","die Adresse","die Adressen","N"],["telephone","das Telefon","die Telefone","N"],
["letter (post)","der Brief","die Briefe","N"],["photo","das Foto","die Fotos","N"],["to belong to","gehören","gehörte · hat gehört","V"],
["to give back","zurückgeben","gibt zurück · gab zurück · hat zurückgegeben","V"],["village","das Dorf","die Dörfer","N"],["square (place)","der Platz","die Plätze","N"],
["way / path","der Weg","die Wege","N"],["bridge","die Brücke","die Brücken","N"],["bus","der Bus","die Busse","N"],
["platform / track","das Gleis","die Gleise","N"],["suitcase","der Koffer","die Koffer","N"],["map","die Landkarte","die Landkarten","N"],
["direction","die Richtung","die Richtungen","N"],["left","links","","B"],["right (direction)","rechts","","B"],
["straight ahead","geradeaus","","B"],["north","der Norden","(kein Plural)","N"],["south","der Süden","(kein Plural)","N"],
["east","der Osten","(kein Plural)","N"],["west","der Westen","(kein Plural)","N"],["border","die Grenze","die Grenzen","N"],
["hotel","das Hotel","die Hotels","N"],["market","der Markt","die Märkte","N"],["supermarket","der Supermarkt","die Supermärkte","N"],
["price","der Preis","die Preise","N"],["cash","das Bargeld","(kein Plural)","N"],["credit card","die Kreditkarte","die Kreditkarten","N"],
["euro","der Euro","die Euro","N"],["discount","der Rabatt","die Rabatte","N"],["size","die Größe","die Größen","N"],
["to depart","abfahren","fährt ab · fuhr ab · ist abgefahren","V"],["to sell","verkaufen","verkaufte · hat verkauft","V"],["to cost","kosten","kostete · hat gekostet","V"],
["to bring","bringen","brachte · hat gebracht","V"],["to carry / wear","tragen","trägt · trug · hat getragen","V"],["to send","schicken","schickte · hat geschickt","V"],
["to stop / hold","halten","hält · hielt · hat gehalten","V"],["to turn off","abbiegen","biegt ab · bog ab · ist abgebogen","V"],["to get on","einsteigen","steigt ein · stieg ein · ist eingestiegen","V"],
["to get off","aussteigen","steigt aus · stieg aus · ist ausgestiegen","V"],["to change (trains)","umsteigen","steigt um · stieg um · ist umgestiegen","V"],["to book","buchen","buchte · hat gebucht","V"],
["near","nah","näher · am nächsten","A"],["far","weit","","A"],["above","oben","","B"],
["below","unten","","B"],["in front","vorne","","B"],["behind","hinten","","B"],
["between","zwischen","+ Dativ / Akkusativ","B"],["next to","neben","+ Dativ / Akkusativ","B"],["opposite","gegenüber","+ Dativ","B"],
["free of charge","kostenlos","","A"],["open","offen","","A"],["closed","geschlossen","","A"],
["full","voll","","A"],["empty","leer","","A"],["seat","der Sitzplatz","die Sitzplätze","N"],
["luggage","das Gepäck","(kein Plural)","N"],["delay","die Verspätung","die Verspätungen","N"],["timetable","der Fahrplan","die Fahrpläne","N"],
["taxi","das Taxi","die Taxis","N"],["petrol station","die Tankstelle","die Tankstellen","N"],["car park","der Parkplatz","die Parkplätze","N"],
["traffic","der Verkehr","(kein Plural)","N"],["traffic light","die Ampel","die Ampeln","N"],["police","die Polizei","(kein Plural)","N"],
["entrance","der Eingang","die Eingänge","N"],["exit","der Ausgang","die Ausgänge","N"],["lift / elevator","der Aufzug","die Aufzüge","N"],
["stairs","die Treppe","die Treppen","N"],["corner","die Ecke","die Ecken","N"],["middle","die Mitte","(kein Plural)","N"],
["tea","der Tee","die Tees","N"],["wine","der Wein","die Weine","N"],["juice","der Saft","die Säfte","N"],
["fish","der Fisch","die Fische","N"],["chicken","das Hähnchen","die Hähnchen","N"],["rice","der Reis","(kein Plural)","N"],
["pasta / noodles","die Nudeln","(nur Plural)","N"],["banana","die Banane","die Bananen","N"],["tomato","die Tomate","die Tomaten","N"],
["onion","die Zwiebel","die Zwiebeln","N"],["salad","der Salat","die Salate","N"],["soup","die Suppe","die Suppen","N"],
["sugar","der Zucker","(kein Plural)","N"],["salt","das Salz","die Salze","N"],["pepper","der Pfeffer","(kein Plural)","N"],
["oil","das Öl","die Öle","N"],["cake","der Kuchen","die Kuchen","N"],["ice cream","das Eis","(kein Plural)","N"],
["chocolate","die Schokolade","die Schokoladen","N"],["breakfast","das Frühstück","die Frühstücke · früh + Stück","N"],["lunch","das Mittagessen","die Mittagessen","N"],
["dinner","das Abendessen","die Abendessen","N"],["plate","der Teller","die Teller","N"],["glass","das Glas","die Gläser","N"],
["cup","die Tasse","die Tassen","N"],["fork","die Gabel","die Gabeln","N"],["knife","das Messer","die Messer","N"],
["spoon","der Löffel","die Löffel","N"],["bottle","die Flasche","die Flaschen","N"],["restaurant","das Restaurant","die Restaurants","N"],
["menu","die Speisekarte","die Speisekarten","N"],["waiter","der Kellner","die Kellner","N"],["hunger","der Hunger","(kein Plural)","N"],
["thirst","der Durst","(kein Plural)","N"],["to bake","backen","bäckt · backte · hat gebacken","V"],["to taste (of)","schmecken","schmeckte · hat geschmeckt","V"],
["to order","bestellen","bestellte · hat bestellt","V"],["hair","die Haare","(meist Plural)","N"],["face","das Gesicht","die Gesichter","N"],
["ear","das Ohr","die Ohren","N"],["nose","die Nase","die Nasen","N"],["mouth","der Mund","die Münder","N"],
["tooth","der Zahn","die Zähne","N"],["neck / throat","der Hals","die Hälse","N"],["shoulder","die Schulter","die Schultern","N"],
["arm","der Arm","die Arme","N"],["finger","der Finger","die Finger","N"],["leg","das Bein","die Beine","N"],
["back (body)","der Rücken","die Rücken","N"],["belly","der Bauch","die Bäuche","N"],["heart","das Herz","die Herzen","N"],
["blood","das Blut","(kein Plural)","N"],["skin","die Haut","die Häute","N"],["bone","der Knochen","die Knochen","N"],
["health","die Gesundheit","(kein Plural)","N"],["illness","die Krankheit","die Krankheiten","N"],["pain","der Schmerz","die Schmerzen","N"],
["fever","das Fieber","(kein Plural)","N"],["cold (illness)","die Erkältung","die Erkältungen","N"],["medicine","das Medikament","die Medikamente","N"],
["appointment","der Termin","die Termine","N"],["nurse","die Krankenschwester","die Krankenschwestern","N"],["to wash","waschen","wäscht · wusch · hat gewaschen","V"],
["to shower","duschen","duschte · hat geduscht","V"],["to get dressed","sich anziehen","zieht sich an · zog sich an · hat sich angezogen","V"],["to rest","sich ausruhen","ruht sich aus · hat sich ausgeruht","V"],
["to hurt","wehtun","tut weh · tat weh · hat wehgetan","V"],["to feel","fühlen","fühlte · hat gefühlt","V"],["to breathe","atmen","atmete · hat geatmet","V"],
["sweet","süß","","A"],["sour","sauer","","A"],["salty","salzig","","A"],
["spicy / sharp","scharf","schärfer · am schärfsten","A"],["warm","warm","wärmer · am wärmsten","A"],["fresh","frisch","","A"],
["sentence","der Satz","die Sätze","N"],["story","die Geschichte","die Geschichten","N"],["news item","die Nachricht","die Nachrichten","N"],
["email","die E-Mail","die E-Mails","N"],["conversation","das Gespräch","die Gespräche","N"],["meeting","das Treffen","die Treffen","N"],
["opinion","die Meinung","die Meinungen","N"],["idea","die Idee","die Ideen","N"],["joke","der Witz","die Witze","N"],
["truth","die Wahrheit","die Wahrheiten","N"],["lie","die Lüge","die Lügen","N"],["secret","das Geheimnis","die Geheimnisse","N"],
["advice","der Rat","die Ratschläge","N"],["help","die Hilfe","(kein Plural)","N"],["apology","die Entschuldigung","die Entschuldigungen","N"],
["mistake","der Fehler","die Fehler","N"],["example","das Beispiel","die Beispiele","N"],["reason","der Grund","die Gründe","N"],
["difference","der Unterschied","die Unterschiede","N"],["solution","die Lösung","die Lösungen","N"],["meaning","die Bedeutung","die Bedeutungen","N"],
["to talk","reden","redete · hat geredet","V"],["to tell","erzählen","erzählte · hat erzählt","V"],["to explain","erklären","erklärte · hat erklärt","V"],
["to be of the opinion","meinen","meinte · hat gemeint","V"],["to remember","sich erinnern","erinnerte sich · hat sich erinnert","V"],["to repeat","wiederholen","wiederholte · hat wiederholt","V"],
["to listen","zuhören","hört zu · hörte zu · hat zugehört","V"],["to meet","treffen","trifft · traf · hat getroffen","V"],["to invite","einladen","lädt ein · lud ein · hat eingeladen","V"],
["to thank","danken","dankte · hat gedankt","V"],["to apologize","sich entschuldigen","entschuldigt sich · hat sich entschuldigt","V"],["to agree","zustimmen","stimmt zu · stimmte zu · hat zugestimmt","V"],
["to refuse","ablehnen","lehnt ab · lehnte ab · hat abgelehnt","V"],["to promise","versprechen","verspricht · versprach · hat versprochen","V"],["to allow","erlauben","erlaubte · hat erlaubt","V"],
["to forbid","verbieten","verbietet · verbot · hat verboten","V"],["to warn","warnen","warnte · hat gewarnt","V"],["to complain","sich beschweren","beschwerte sich · hat sich beschwert","V"],
["to laugh","lachen","lachte · hat gelacht","V"],["to cry","weinen","weinte · hat geweint","V"],["to smile","lächeln","lächelte · hat gelächelt","V"],
["to greet","grüßen","grüßte · hat gegrüßt","V"],["to introduce","vorstellen","stellt vor · stellte vor · hat vorgestellt","V"],["to discuss","diskutieren","diskutierte · hat diskutiert","V"],
["to decide","entscheiden","entscheidet · entschied · hat entschieden","V"],["to describe","beschreiben","beschreibt · beschrieb · hat beschrieben","V"],["to compare","vergleichen","vergleicht · verglich · hat verglichen","V"],
["to translate","übersetzen","übersetzte · hat übersetzt","V"],["to spell","buchstabieren","buchstabierte · hat buchstabiert","V"],["to show","zeigen","zeigte · hat gezeigt","V"],
["to mention","erwähnen","erwähnte · hat erwähnt","V"],["clear","klar","","A"],["true","wahr","","A"],
["polite","höflich","","A"],["friendly","freundlich","","A"],["impolite","unhöflich","","A"],
["funny","lustig","","A"],["serious","ernst","","A"],["strange","seltsam","","A"],
["interesting","interessant","","A"],["boring","langweilig","","A"],["possible","möglich","","A"],
["impossible","unmöglich","","A"],["certain / safe","sicher","","A"],["maybe","vielleicht","","B"],
["of course","natürlich","","B"],["really","wirklich","","B"],["actually","eigentlich","","B"],
["for example","zum Beispiel","","B"],["first of all","zuerst","","B"],["then","dann","","B"],
["finally","schließlich","","B"],["because","weil","Nebensatz: Verb am Ende","B"],["although","obwohl","Nebensatz: Verb am Ende","B"],
["if / when","wenn","Nebensatz: Verb am Ende","B"],["that (conjunction)","dass","Nebensatz: Verb am Ende","B"],["or","oder","","B"],
["so / therefore","also","","B"],["by the way","übrigens","","B"],["at least","wenigstens","","B"],
["together","zusammen","","B"],["again","wieder","","B"],["only","nur","","B"],
// ── Bands 7–10 · Werkstatt · Vorstoß · Denkfabrik · Feldherr (append-only) ──
["company","die Firma","die Firmen","N"],["office","das Büro","die Büros","N"],["boss","der Chef","die Chefs","N"],
["colleague (m)","der Kollege","die Kollegen","N"],["colleague (f)","die Kollegin","die Kolleginnen","N"],["profession","der Beruf","die Berufe","N"],
["position / post","die Stelle","die Stellen","N"],["contract","der Vertrag","die Verträge","N"],["salary","das Gehalt","die Gehälter","N"],
["wage","der Lohn","die Löhne","N"],["tax","die Steuer","die Steuern","N"],["insurance","die Versicherung","die Versicherungen","N"],
["meeting (business)","die Besprechung","die Besprechungen","N"],["plan","der Plan","die Pläne","N"],["goal","das Ziel","die Ziele","N"],
["task","die Aufgabe","die Aufgaben","N"],["project","das Projekt","die Projekte","N"],["deadline","die Frist","die Fristen","N"],
["calendar","der Kalender","die Kalender","N"],["customer","der Kunde","die Kunden","N"],["order (commercial)","der Auftrag","die Aufträge","N"],
["delivery","die Lieferung","die Lieferungen","N"],["warehouse","das Lager","die Lager","N"],["machine","die Maschine","die Maschinen","N"],
["tool","das Werkzeug","die Werkzeuge","N"],["material","das Material","die Materialien","N"],["quality","die Qualität","die Qualitäten","N"],
["quantity","die Menge","die Mengen","N"],["weight","das Gewicht","die Gewichte","N"],["costs","die Kosten","(nur Plural)","N"],
["profit","der Gewinn","die Gewinne","N"],["loss","der Verlust","die Verluste","N"],["result","das Ergebnis","die Ergebnisse","N"],
["report","der Bericht","die Berichte","N"],["note","die Notiz","die Notizen","N"],["signature","die Unterschrift","die Unterschriften","N"],
["form (document)","das Formular","die Formulare","N"],["application (formal)","der Antrag","die Anträge","N"],["permission","die Genehmigung","die Genehmigungen","N"],
["ID card","der Ausweis","die Ausweise","N"],["job application","die Bewerbung","die Bewerbungen","N"],["certificate","das Zeugnis","die Zeugnisse","N"],
["training","die Ausbildung","die Ausbildungen","N"],["internship","das Praktikum","die Praktika","N"],["university","die Universität","die Universitäten","N"],
["course","der Kurs","die Kurse","N"],["lecture","die Vorlesung","die Vorlesungen","N"],["exam","die Prüfung","die Prüfungen","N"],
["grade / mark","die Note","die Noten","N"],["subject (school)","das Fach","die Fächer","N"],["library","die Bibliothek","die Bibliotheken","N"],
["notebook","das Heft","die Hefte","N"],["pen","der Stift","die Stifte","N"],["printer","der Drucker","die Drucker","N"],
["keyboard","die Tastatur","die Tastaturen","N"],["screen","der Bildschirm","die Bildschirme","N"],["file (computer)","die Datei","die Dateien","N"],
["folder","der Ordner","die Ordner","N"],["programme","das Programm","die Programme","N"],["software","die Software","(kein Plural)","N"],
["internet","das Internet","(kein Plural)","N"],["website","die Webseite","die Webseiten","N"],["password","das Passwort","die Passwörter","N"],
["electricity","der Strom","(kein Plural)","N"],["repair","die Reparatur","die Reparaturen","N"],["workshop","die Werkstatt","die Werkstätten","N"],
["break","die Pause","die Pausen","N"],["holiday / leave","der Urlaub","die Urlaube","N"],["shift","die Schicht","die Schichten","N"],
["overtime","die Überstunde","die Überstunden","N"],["team","das Team","die Teams","N"],["department","die Abteilung","die Abteilungen","N"],
["safety","die Sicherheit","(kein Plural)","N"],["accident","der Unfall","die Unfälle","N"],["to earn","verdienen","verdiente · hat verdient","V"],
["to finish","beenden","beendete · hat beendet","V"],["to plan","planen","plante · hat geplant","V"],["to organize","organisieren","organisierte · hat organisiert","V"],
["to check","prüfen","prüfte · hat geprüft","V"],["to change (alter)","ändern","änderte · hat geändert","V"],["to improve","verbessern","verbesserte · hat verbessert","V"],
["to develop","entwickeln","entwickelte · hat entwickelt","V"],["to produce","herstellen","stellt her · stellte her · hat hergestellt","V"],["to use","benutzen","benutzte · hat benutzt","V"],
["to repair","reparieren","reparierte · hat repariert","V"],["to measure","messen","misst · maß · hat gemessen","V"],["to weigh","wiegen","wiegt · wog · hat gewogen","V"],
["to deliver","liefern","lieferte · hat geliefert","V"],["to calculate","rechnen","rechnete · hat gerechnet","V"],["to sign","unterschreiben","unterschreibt · unterschrieb · hat unterschrieben","V"],
["to print","drucken","druckte · hat gedruckt","V"],["to save (file)","speichern","speicherte · hat gespeichert","V"],["to delete","löschen","löschte · hat gelöscht","V"],
["to copy","kopieren","kopierte · hat kopiert","V"],["to work (function)","funktionieren","funktionierte · hat funktioniert","V"],["to resign / cancel","kündigen","kündigte · hat gekündigt","V"],
["to manage / cope","schaffen","schaffte · hat geschafft","V"],["to practise","üben","übte · hat geübt","V"],["to study (at university)","studieren","studierte · hat studiert","V"],
["to teach","unterrichten","unterrichtete · hat unterrichtet","V"],["to pass (an exam)","bestehen","besteht · bestand · hat bestanden","V"],["to lead / manage","leiten","leitete · hat geleitet","V"],
["to take part","teilnehmen","nimmt teil · nahm teil · hat teilgenommen","V"],["ready / finished","fertig","","A"],["punctual","pünktlich","","A"],
["reliable","zuverlässig","","A"],["tidy","ordentlich","","A"],["exact","genau","","A"],
["cheap / favourable","günstig","","A"],["necessary","nötig","","A"],["urgent","dringend","","A"],
["busy","beschäftigt","","A"],["unemployed","arbeitslos","","A"],["self-employed","selbstständig","","A"],
["experienced","erfahren","","A"],["responsible","verantwortlich","","A"],["possible (feasible)","machbar","","A"],
["complicated","kompliziert","","A"],["to come back","zurückkommen","kommt zurück · kam zurück · ist zurückgekommen","V"],["to come along","mitkommen","kommt mit · kam mit · ist mitgekommen","V"],
["to bring along","mitbringen","bringt mit · brachte mit · hat mitgebracht","V"],["to take along","mitnehmen","nimmt mit · nahm mit · hat mitgenommen","V"],["to go away","weggehen","geht weg · ging weg · ist weggegangen","V"],
["to go out","ausgehen","geht aus · ging aus · ist ausgegangen","V"],["to come in","hereinkommen","kommt herein · kam herein · ist hereingekommen","V"],["to open (something)","aufmachen","macht auf · machte auf · hat aufgemacht","V"],
["to close (something)","zumachen","macht zu · machte zu · hat zugemacht","V"],["to switch on","anmachen","macht an · machte an · hat angemacht","V"],["to switch off","ausmachen","macht aus · machte aus · hat ausgemacht","V"],
["to tidy up","aufräumen","räumt auf · räumte auf · hat aufgeräumt","V"],["to pay attention","aufpassen","passt auf · passte auf · hat aufgepasst","V"],["to fill in","ausfüllen","füllt aus · füllte aus · hat ausgefüllt","V"],
["to pick up / collect","abholen","holt ab · holte ab · hat abgeholt","V"],["to take off (clothes)","ausziehen","zieht aus · zog aus · hat ausgezogen","V"],["to move house","umziehen","zieht um · zog um · ist umgezogen","V"],
["to move in","einziehen","zieht ein · zog ein · ist eingezogen","V"],["to wake up","aufwachen","wacht auf · wachte auf · ist aufgewacht","V"],["to fall asleep","einschlafen","schläft ein · schlief ein · ist eingeschlafen","V"],
["to sleep in","ausschlafen","schläft aus · schlief aus · hat ausgeschlafen","V"],["to carry on","weitermachen","macht weiter · machte weiter · hat weitergemacht","V"],["to lose weight / take off","abnehmen","nimmt ab · nahm ab · hat abgenommen","V"],
["to put on weight / increase","zunehmen","nimmt zu · nahm zu · hat zugenommen","V"],["to prepare","vorbereiten","bereitet vor · bereitete vor · hat vorbereitet","V"],["to arrange to meet","sich verabreden","verabredet sich · hat sich verabredet","V"],
["to register","sich anmelden","meldet sich an · hat sich angemeldet","V"],["to deregister","sich abmelden","meldet sich ab · hat sich abgemeldet","V"],["to spend (money)","ausgeben","gibt aus · gab aus · hat ausgegeben","V"],
["to go shopping","einkaufen","kauft ein · kaufte ein · hat eingekauft","V"],["to borrow / lend out","ausleihen","leiht aus · lieh aus · hat ausgeliehen","V"],["to exchange","umtauschen","tauscht um · tauschte um · hat umgetauscht","V"],
["to look (appear)","aussehen","sieht aus · sah aus · hat ausgesehen","V"],["to please / like","gefallen","gefällt · gefiel · hat gefallen","V"],["to fit / suit","passen","passte · hat gepasst","V"],
["to take place","stattfinden","findet statt · fand statt · hat stattgefunden","V"],["to give up","aufgeben","gibt auf · gab auf · hat aufgegeben","V"],["to cooperate","zusammenarbeiten","arbeitet zusammen · hat zusammengearbeitet","V"],
["to know one's way around","sich auskennen","kennt sich aus · hat sich ausgekannt","V"],["to find out","herausfinden","findet heraus · fand heraus · hat herausgefunden","V"],["to think about","nachdenken","denkt nach · dachte nach · hat nachgedacht","V"],
["to ask again / enquire","nachfragen","fragt nach · fragte nach · hat nachgefragt","V"],["to watch","zuschauen","schaut zu · schaute zu · hat zugeschaut","V"],["to throw away","wegwerfen","wirft weg · warf weg · hat weggeworfen","V"],
["to break (something)","kaputtmachen","macht kaputt · machte kaputt · hat kaputtgemacht","V"],["to invite along","einladen zu","lädt ein · lud ein · hat eingeladen","V"],["rent","die Miete","die Mieten","N"],
["landlord","der Vermieter","die Vermieter","N"],["deposit","die Kaution","die Kautionen","N"],["heating","die Heizung","die Heizungen","N"],
["bank account","das Konto","die Konten","N"],["bank","die Bank","die Banken","N"],["bank transfer","die Überweisung","die Überweisungen","N"],
["cash machine","der Geldautomat","die Geldautomaten","N"],["post office","die Post","(kein Plural)","N"],["parcel","das Paket","die Pakete","N"],
["public office","das Amt","die Ämter","N"],["registration","die Anmeldung","die Anmeldungen","N"],["passport","der Pass","die Pässe","N"],
["visa","das Visum","die Visa","N"],["health insurance fund","die Krankenkasse","die Krankenkassen","N"],["move (relocation)","der Umzug","die Umzüge","N"],
["caretaker","der Hausmeister","die Hausmeister","N"],["rubbish","der Müll","(kein Plural)","N"],["order (tidiness)","die Ordnung","(kein Plural)","N"],
["permission slip","die Erlaubnis","die Erlaubnisse","N"],["emergency","der Notfall","die Notfälle","N"],["grown-up","erwachsen","","A"],
["in charge of","zuständig","","A"],["practical","praktisch","","A"],["independent","unabhängig","","A"],
["allowed","erlaubt","","A"],["forbidden","verboten","","A"],["possibility","die Möglichkeit","die Möglichkeiten","N"],
["part","der Teil","die Teile","N"],["kind / type","die Art","die Arten","N"],["way / manner","die Weise","die Weisen","N"],
["sense / point","der Sinn","(kein Plural)","N"],["purpose","der Zweck","die Zwecke","N"],["intention","die Absicht","die Absichten","N"],
["consequence","die Folge","die Folgen","N"],["cause","die Ursache","die Ursachen","N"],["effect","die Wirkung","die Wirkungen","N"],
["state / condition","der Zustand","die Zustände","N"],["situation","die Situation","die Situationen","N"],["case","der Fall","die Fälle","N"],
["condition (prerequisite)","die Bedingung","die Bedingungen","N"],["advantage","der Vorteil","die Vorteile","N"],["disadvantage","der Nachteil","die Nachteile","N"],
["similarity","die Ähnlichkeit","die Ähnlichkeiten","N"],["relationship","die Beziehung","die Beziehungen","N"],["connection","die Verbindung","die Verbindungen","N"],
["development","die Entwicklung","die Entwicklungen","N"],["change","die Veränderung","die Veränderungen","N"],["experience","die Erfahrung","die Erfahrungen","N"],
["experience (event)","das Erlebnis","die Erlebnisse","N"],["feeling","das Gefühl","die Gefühle","N"],["thought","der Gedanke","die Gedanken","N"],
["memory","die Erinnerung","die Erinnerungen","N"],["hope","die Hoffnung","die Hoffnungen","N"],["wish","der Wunsch","die Wünsche","N"],
["interest","das Interesse","die Interessen","N"],["attention","die Aufmerksamkeit","(kein Plural)","N"],["patience","die Geduld","(kein Plural)","N"],
["effort","die Mühe","die Mühen","N"],["success","der Erfolg","die Erfolge","N"],["trust","das Vertrauen","(kein Plural)","N"],
["responsibility","die Verantwortung","(kein Plural)","N"],["freedom","die Freiheit","die Freiheiten","N"],["justice","die Gerechtigkeit","(kein Plural)","N"],
["right (entitlement)","das Recht","die Rechte","N"],["duty","die Pflicht","die Pflichten","N"],["society","die Gesellschaft","die Gesellschaften","N"],
["politics","die Politik","(kein Plural)","N"],["economy","die Wirtschaft","(kein Plural)","N"],["environment","die Umwelt","(kein Plural)","N"],
["nature","die Natur","(kein Plural)","N"],["climate","das Klima","die Klimate","N"],["energy","die Energie","die Energien","N"],
["future","die Zukunft","(kein Plural)","N"],["past","die Vergangenheit","(kein Plural)","N"],["present (time)","die Gegenwart","(kein Plural)","N"],
["century","das Jahrhundert","die Jahrhunderte","N"],["culture","die Kultur","die Kulturen","N"],["art","die Kunst","die Künste","N"],
["science","die Wissenschaft","die Wissenschaften","N"],["research","die Forschung","die Forschungen","N"],["per cent","das Prozent","die Prozente","N"],
["average","der Durchschnitt","die Durchschnitte","N"],["nevertheless","trotzdem","","B"],["therefore","deshalb","","B"],
["besides","außerdem","","B"],["however","jedoch","","B"],["otherwise","sonst","","B"],
["anyway","sowieso","","B"],["at any rate","immerhin","","B"],["admittedly","allerdings","","B"],
["at least (minimum)","zumindest","","B"],["on the one hand","einerseits","","B"],["on the other hand","andererseits","","B"],
["luckily","zum Glück","","B"],["unfortunately","leider","","B"],["hopefully","hoffentlich","","B"],
["certainly","bestimmt","","B"],["absolutely","unbedingt","","B"],["hardly","kaum","","B"],
["quite / fairly","ziemlich","","B"],["especially","besonders","","B"],["approximately","ungefähr","","B"],
["at least (amount)","mindestens","","B"],["at most","höchstens","","B"],["mostly","meistens","","B"],
["normally","normalerweise","","B"],["suddenly","plötzlich","","B"],["at last","endlich","","B"],
["just now","gerade","","B"],["immediately","sofort","","B"],["back then","damals","","B"],
["formerly","früher","","B"],["recently","neulich","","B"],["meanwhile","inzwischen","","B"],
["at the same time","gleichzeitig","","B"],["at all","überhaupt","","B"],["rather","eher","","B"],
["preferably","lieber","","B"],["probable","wahrscheinlich","","A"],["different (various)","verschieden","","A"],
["similar","ähnlich","","A"],["same","gleich","","A"],["individual","einzeln","","A"],
["joint / common","gemeinsam","","A"],["general","allgemein","","A"],["typical","typisch","","A"],
["normal","normal","","A"],["clear (distinct)","deutlich","","A"],["sensible","sinnvoll","","A"],
["useful","nützlich","","A"],["harmful","schädlich","","A"],["dangerous","gefährlich","","A"],
["deep","tief","","A"],["to reach / achieve","erreichen","erreichte · hat erreicht","V"],["to receive","erhalten","erhält · erhielt · hat erhalten","V"],
["to offer","anbieten","bietet an · bot an · hat angeboten","V"],["to lead / guide","führen","führte · hat geführt","V"],["to apply / be valid","gelten","gilt · galt · hat gegolten","V"],
["to concern","betreffen","betrifft · betraf · hat betroffen","V"],["to consist of","bestehen aus","besteht aus · bestand aus · hat bestanden","V"],["to contain","enthalten","enthält · enthielt · hat enthalten","V"],
["to arise","entstehen","entsteht · entstand · ist entstanden","V"],["to expect","erwarten","erwartete · hat erwartet","V"],["to be missing","fehlen","fehlte · hat gefehlt","V"],
["to follow","folgen","folgte · ist gefolgt","V"],["to succeed","gelingen","gelingt · gelang · ist gelungen","V"],["to happen","geschehen","geschieht · geschah · ist geschehen","V"],
["to act","handeln","handelte · hat gehandelt","V"],["to hang","hängen","hängt · hing · hat gehangen","V"],["to fetch","holen","holte · hat geholt","V"],
["to hope","hoffen","hoffte · hat gehofft","V"],["to fight","kämpfen","kämpfte · hat gekämpft","V"],["to sound","klingen","klingt · klang · hat geklungen","V"],
["to let / leave","lassen","lässt · ließ · hat gelassen","V"],["to lay / put down","legen","legte · hat gelegt","V"],["to lie (be situated)","liegen","liegt · lag · hat gelegen","V"],
["to notice","merken","merkte · hat gemerkt","V"],["to use / make use of","nutzen","nutzte · hat genutzt","V"],["to be enough","reichen","reichte · hat gereicht","V"],
["to save / rescue","retten","rettete · hat gerettet","V"],["to seem","scheinen","scheint · schien · hat geschienen","V"],["to hit / beat","schlagen","schlägt · schlug · hat geschlagen","V"],
["to cut","schneiden","schneidet · schnitt · hat geschnitten","V"],["to set / put","setzen","setzte · hat gesetzt","V"],["to sit","sitzen","sitzt · saß · hat gesessen","V"],
["to take care of","sorgen für","sorgte · hat gesorgt","V"],["to stand","stehen","steht · stand · hat gestanden","V"],["to rise / climb","steigen","steigt · stieg · ist gestiegen","V"],
["to place upright","stellen","stellte · hat gestellt","V"],["to die","sterben","stirbt · starb · ist gestorben","V"],["to be correct","stimmen","stimmte · hat gestimmt","V"],
["to disturb","stören","störte · hat gestört","V"],["to share / divide","teilen","teilte · hat geteilt","V"],["to step","treten","tritt · trat · ist getreten","V"],
["to do","tun","tut · tat · hat getan","V"],["to distinguish","unterscheiden","unterscheidet · unterschied · hat unterschieden","V"],["to change / alter","verändern","veränderte · hat verändert","V"],
["to connect / join","verbinden","verbindet · verband · hat verbunden","V"],["to pass (time)","vergehen","vergeht · verging · ist vergangen","V"],["to demand","verlangen","verlangte · hat verlangt","V"],
["to leave (a place)","verlassen","verlässt · verließ · hat verlassen","V"],["to avoid","vermeiden","vermeidet · vermied · hat vermieden","V"],["to use / apply","verwenden","verwendete · hat verwendet","V"],
["to grow","wachsen","wächst · wuchs · ist gewachsen","V"],["to choose / elect","wählen","wählte · hat gewählt","V"],["to change / swap","wechseln","wechselte · hat gewechselt","V"],
["to throw","werfen","wirft · warf · hat geworfen","V"],["to have an effect","wirken","wirkte · hat gewirkt","V"],["to wish","wünschen","wünschte · hat gewünscht","V"],
["to pay (an amount)","zahlen","zahlte · hat gezahlt","V"],["to pull","ziehen","zieht · zog · hat gezogen","V"],["to force","zwingen","zwingt · zwang · hat gezwungen","V"],
["to hold on / stop","anhalten","hält an · hielt an · hat angehalten","V"],["area / field","der Bereich","die Bereiche","N"],["role","die Rolle","die Rollen","N"],
["strength / force","die Kraft","die Kräfte","N"],["power","die Macht","die Mächte","N"],["value","der Wert","die Werte","N"],
["means","das Mittel","die Mittel","N"],["thing","das Ding","die Dinge","N"],["matter / affair","die Sache","die Sachen","N"],
["place / spot","der Ort","die Orte","N"],["side / page","die Seite","die Seiten","N"],["piece","das Stück","die Stücke","N"],
["row / series","die Reihe","die Reihen","N"],["pair","das Paar","die Paare","N"],["half (noun)","die Hälfte","die Hälften","N"],
["end","das Ende","die Enden","N"],["beginning","der Anfang","die Anfänge","N"],["rest / remainder","der Rest","die Reste","N"],
["degree","der Grad","die Grade","N"],["level / stage","die Stufe","die Stufen","N"],["step","der Schritt","die Schritte","N"],
["attempt","der Versuch","die Versuche","N"],["choice / election","die Wahl","die Wahlen","N"],["suggestion","der Vorschlag","die Vorschläge","N"],
["decision","die Entscheidung","die Entscheidungen","N"],["difficulty","die Schwierigkeit","die Schwierigkeiten","N"],["opportunity / chance","die Chance","die Chancen","N"],
["danger","die Gefahr","die Gefahren","N"],["luck","das Glück","(kein Plural)","N"],["bad luck","das Pech","(kein Plural)","N"],
["nonsense","der Unsinn","(kein Plural)","N"],["kind (sort)","die Sorte","die Sorten","N"],["group","die Gruppe","die Gruppen","N"],
["member","das Mitglied","die Mitglieder","N"],["neighbourhood","die Umgebung","die Umgebungen","N"],["distance","die Entfernung","die Entfernungen","N"],
["speed","die Geschwindigkeit","die Geschwindigkeiten","N"],["strong","stark","stärker · am stärksten","A"],["weak","schwach","schwächer · am schwächsten","A"],
["wide / broad","breit","","A"],["narrow","eng","","A"],["high","hoch","höher · am höchsten","A"],
["low","niedrig","","A"],["long","lang","länger · am längsten","A"],["short","kurz","kürzer · am kürzesten","A"],
["heavy / difficult","schwierig","","A"],["quiet / silent","still","","A"],["fair","gerecht","","A"],
["unfair","ungerecht","","A"],["honest","ehrlich","","A"],["proud","stolz","","A"],
["curious","neugierig","","A"],["brave","mutig","","A"],["careful","vorsichtig","","A"],
["lazy","faul","","A"],["hard-working","fleißig","","A"],["patient","geduldig","","A"],
["satisfied","zufrieden","","A"],["disappointed","enttäuscht","","A"],["surprised","überrascht","","A"],
["angry","wütend","","A"],["worried","besorgt","","A"],["relaxed","entspannt","","A"]
];
