// BuddyLingo German deck — built per "Ultimate German Vocabulary Module" (docs/german guide)
// Entry: [english, german lemma (nouns: with article), forms (nouns: plural · verbs: parts/government), cat]
// Rules honored: gender inherent (article shown from encounter 1), plural stored day one,
// separable verbs shown split, compounds after constituents, semantic neighbours interleaved.
window.TIER_NAMES = ["Grundausbildung", "Feldzug"];
window.DECK = [
// ── Tier 1 · A1 · Grundausbildung (100) ──
["hello","hallo","","B"],
["thank you","danke","","B"],
["yes","ja","","B"],
["no","nein","","B"],
["please / you're welcome","bitte","","B"],
["good","gut","","A"],
["to be","sein","ist · war · ist gewesen","V"],
["to have","haben","hat · hatte · gehabt","V"],
["and","und","","B"],
["not","nicht","","B"],
["water","das Wasser","(no plural)","N"],
["bread","das Brot","die Brote","N"],
["house","das Haus","die Häuser","N"],
["man","der Mann","die Männer","N"],
["woman","die Frau","die Frauen","N"],
["child","das Kind","die Kinder","N"],
["day","der Tag","die Tage","N"],
["night","die Nacht","die Nächte","N"],
["to go","gehen","ging · ist gegangen","V"],
["to come","kommen","kam · ist gekommen","V"],
["to make / to do","machen","machte · gemacht","V"],
["to say","sagen","sagte · gesagt","V"],
["big","groß","","A"],
["small","klein","","A"],
["new","neu","","A"],
["old","alt","","A"],
["city","die Stadt","die Städte","N"],
["railway station","der Bahnhof","die Bahnhöfe","N"],
["train","der Zug","die Züge","N"],
["street","die Straße","die Straßen","N"],
["time","die Zeit","die Zeiten","N"],
["year","das Jahr","die Jahre","N"],
["to eat","essen","isst · aß · gegessen","V"],
["to drink","trinken","trank · getrunken","V"],
["to see","sehen","sieht · sah · gesehen","V"],
["to speak","sprechen","spricht · sprach · gesprochen","V"],
["language","die Sprache","die Sprachen","N"],
["friend","der Freund","die Freunde","N"],
["good morning","guten Morgen","","B"],
["good evening","guten Abend","","B"],
["goodbye","auf Wiedersehen","","B"],
["excuse me / sorry","Entschuldigung","","B"],
["how are you?","wie geht's?","","B"],
["money","das Geld","(no plural)","N"],
["work","die Arbeit","die Arbeiten","N"],
["to work","arbeiten","arbeitete · gearbeitet","V"],
["school","die Schule","die Schulen","N"],
["book","das Buch","die Bücher","N"],
["to read","lesen","liest · las · gelesen","V"],
["to write","schreiben","schrieb · geschrieben","V"],
["to buy","kaufen","kaufte · gekauft","V"],
["to get up","aufstehen","steht auf · stand auf · ist aufgestanden","V"],
["morning","der Morgen","die Morgen","N"],
["evening","der Abend","die Abende","N"],
["week","die Woche","die Wochen","N"],
["month","der Monat","die Monate","N"],
["today","heute","","A"],
["tomorrow","morgen","","A"],
["yesterday","gestern","","A"],
["here","hier","","A"],
["there","dort","","A"],
["where?","wo?","","B"],
["what?","was?","","B"],
["who?","wer?","","B"],
["why?","warum?","","B"],
["how?","wie?","","B"],
["food","das Essen","(no plural)","N"],
["apple","der Apfel","die Äpfel","N"],
["milk","die Milch","(no plural)","N"],
["coffee","der Kaffee","die Kaffees","N"],
["beer","das Bier","die Biere","N"],
["table","der Tisch","die Tische","N"],
["chair","der Stuhl","die Stühle","N"],
["door","die Tür","die Türen","N"],
["window","das Fenster","die Fenster","N"],
["car","das Auto","die Autos","N"],
["to drive / to ride","fahren","fährt · fuhr · ist gefahren","V"],
["to live (reside)","wohnen","wohnte · gewohnt","V"],
["to love","lieben","liebte · geliebt","V"],
["to need","brauchen","brauchte · gebraucht","V"],
["to give","geben","gibt · gab · gegeben","V"],
["to take","nehmen","nimmt · nahm · genommen","V"],
["to find","finden","fand · gefunden","V"],
["to know (a fact)","wissen","weiß · wusste · gewusst","V"],
["to know (a person)","kennen","kannte · gekannt","V"],
["beautiful","schön","","A"],
["bad","schlecht","","A"],
["fast","schnell","","A"],
["slow","langsam","","A"],
["expensive","teuer","","A"],
["cheap","billig","","A"],
["hot","heiß","","A"],
["cold","kalt","","A"],
["right / correct","richtig","","A"],
["wrong","falsch","","A"],
["family","die Familie","die Familien","N"],
["mother","die Mutter","die Mütter","N"],
["father","der Vater","die Väter","N"],
["dog","der Hund","die Hunde","N"],
["to sleep","schlafen","schläft · schlief · geschlafen","V"],
["to help","helfen","hilft · half · geholfen · jemandem (Dat.)","V"],
// ── Tier 2 · A2 · Feldzug (100) ──
["brother","der Bruder","die Brüder","N"],
["sister","die Schwester","die Schwestern","N"],
["cat","die Katze","die Katzen","N"],
["name","der Name","die Namen","N"],
["number","die Zahl","die Zahlen","N"],
["weather","das Wetter","(no plural)","N"],
["rain","der Regen","(no plural)","N"],
["sun","die Sonne","die Sonnen","N"],
["to become","werden","wird · wurde · ist geworden","V"],
["to stay","bleiben","blieb · ist geblieben","V"],
["to think","denken","dachte · gedacht","V"],
["to believe","glauben","glaubte · geglaubt","V"],
["to understand","verstehen","verstand · verstanden","V"],
["to answer","antworten","antwortete · geantwortet","V"],
["question","die Frage","die Fragen","N"],
["answer","die Antwort","die Antworten","N"],
["to ask","fragen","fragte · gefragt","V"],
["to wait","warten","wartete · gewartet · auf + Akk.","V"],
["to begin","anfangen","fängt an · fing an · angefangen","V"],
["to stop (doing)","aufhören","hörte auf · aufgehört · mit + Dat.","V"],
["to arrive","ankommen","kam an · ist angekommen","V"],
["to call (phone)","anrufen","rief an · angerufen","V"],
["airport","der Flughafen","die Flughäfen","N"],
["main station","der Hauptbahnhof","die Hauptbahnhöfe · Haupt + Bahnhof","N"],
["world","die Welt","die Welten","N"],
["country","das Land","die Länder","N"],
["trip / journey","die Reise","die Reisen","N"],
["to travel","reisen","reiste · ist gereist","V"],
["ticket (travel)","die Fahrkarte","die Fahrkarten · fahren + Karte","N"],
["bicycle","das Fahrrad","die Fahrräder · fahren + Rad","N"],
["driver","der Fahrer","die Fahrer · from fahren","N"],
["departure","die Abfahrt","die Abfahrten · from abfahren","N"],
["key","der Schlüssel","die Schlüssel","N"],
["room","das Zimmer","die Zimmer","N"],
["kitchen","die Küche","die Küchen","N"],
["bathroom","das Bad","die Bäder","N"],
["apartment","die Wohnung","die Wohnungen · from wohnen","N"],
["building","das Gebäude","die Gebäude","N"],
["to open","öffnen","öffnete · geöffnet","V"],
["to close","schließen","schloss · geschlossen","V"],
["to pay","bezahlen","bezahlte · bezahlt","V"],
["bill / invoice","die Rechnung","die Rechnungen","N"],
["shop / store","das Geschäft","die Geschäfte","N"],
["bakery","die Bäckerei","die Bäckereien","N"],
["meat","das Fleisch","(no plural)","N"],
["vegetables","das Gemüse","(no plural)","N"],
["fruit","das Obst","(no plural)","N"],
["cheese","der Käse","(no plural)","N"],
["egg","das Ei","die Eier","N"],
["butter","die Butter","(no plural)","N"],
["sausage","die Wurst","die Würste","N"],
["pretzel","die Brezel","die Brezeln","N"],
["potato","die Kartoffel","die Kartoffeln","N"],
["to cook","kochen","kochte · gekocht","V"],
["delicious","lecker","","A"],
["hungry","hungrig","","A"],
["thirsty","durstig","","A"],
["tired","müde","","A"],
["sick","krank","","A"],
["healthy","gesund","","A"],
["doctor","der Arzt","die Ärzte","N"],
["hospital","das Krankenhaus","die Krankenhäuser · krank + Haus","N"],
["pharmacy","die Apotheke","die Apotheken","N"],
["body","der Körper","die Körper","N"],
["head","der Kopf","die Köpfe","N"],
["hand","die Hand","die Hände","N"],
["foot","der Fuß","die Füße","N"],
["eye","das Auge","die Augen","N"],
["to hear","hören","hörte · gehört","V"],
["music","die Musik","(no plural)","N"],
["to play","spielen","spielte · gespielt","V"],
["game","das Spiel","die Spiele","N"],
["to win","gewinnen","gewann · gewonnen","V"],
["to lose","verlieren","verlor · verloren","V"],
["to run","laufen","läuft · lief · ist gelaufen","V"],
["to swim","schwimmen","schwamm · ist geschwommen","V"],
["mountain","der Berg","die Berge","N"],
["sea","das Meer","die Meere","N"],
["forest","der Wald","die Wälder","N"],
["tree","der Baum","die Bäume","N"],
["flower","die Blume","die Blumen","N"],
["bird","der Vogel","die Vögel","N"],
["to fly","fliegen","flog · ist geflogen","V"],
["airplane","das Flugzeug","die Flugzeuge · Flug + Zeug","N"],
["difficult / heavy","schwer","","A"],
["easy / light","leicht","","A"],
["important","wichtig","","A"],
["to forget","vergessen","vergisst · vergaß · vergessen","V"],
["to learn","lernen","lernte · gelernt","V"],
["free","frei","","A"],
["always","immer","","A"],
["victory","der Sieg","die Siege","N"],
["often","oft","","A"],
["dictionary","das Wörterbuch","die Wörterbücher · Wort + Buch","N"],
["now","jetzt","","A"],
["later","später","","A"],
["war","der Krieg","die Kriege","N"],
["word","das Wort","die Wörter","N"],
["to try","versuchen","versuchte · versucht","V"]
];
