// BuddyLingo Tunisian (Tounsi/Derja) deck — per "Tunisian Arabic Vocab Crunch" guide
// Entry: [english, latin canonical (learner romanisation: 3=ع 7=ح 9=ق kh=خ ch=ش), arabic script · accepted aliases, cat]
// PROVISIONAL: forms follow common Arabizi usage; needs native (Cap Bon) verification per guide.
// One lexical brain: latin shown as target, arabic script shown as secondary form.
window.TIER_NAMES = ["El Assess"];
window.DECK = [
["hello","3asslema","عالسلامة · also: asslema","B"],
["welcome","mar7ba","مرحبا","B"],
["thank you","y3aychek","يعيشك · also: aychek","B"],
["yes","ey","أي · also: ay","B"],
["no","le","لا · also: la","B"],
["please","brabbi","بربّي","B"],
["good / fine","behi","باهي · also: bahi","A"],
["a lot","barsha","برشا · also: barcha","A"],
["a little","chwaya","شوية · also: shwaya","A"],
["enough!","yezzi","يزّي","B"],
["there is","famma","فمّا · also: fama","B"],
["work","khedma","خدمة · also: 5edma","N"],
["money","flous","فلوس","N"],
["bread","khobz","خبز · also: 5obz","N"],
["water","me","ماء · also: ma","N"],
["milk","7lib","حليب","N"],
["coffee","9ahwa","قهوة · also: kahwa","N"],
["tea","tey","تاي","N"],
["fish","7out","حوت","N"],
["meat","l7am","لحم","N"],
["couscous","kosksi","كسكسي · also: couscous","N"],
["harissa","harissa","هريسة","N"],
["brik (pastry)","brik","بريك","N"],
["olive oil","zit zitouna","زيت زيتونة","N"],
["house","dar","دار","N"],
["room","bit","بيت — careful: bit = room, dar = house","N"],
["door","beb","باب","N"],
["key","mefte7","مفتاح · also: mefta7","N"],
["car","karhba","كرهبة","N"],
["market","sou9","سوق · also: souk","N"],
["day","nhar","نهار","N"],
["night","lil","ليل · also: lila","N"],
["today","lyoum","اليوم · also: el youm","A"],
["tomorrow","ghodwa","غدوة","A"],
["yesterday","lbera7","البارح · also: el bare7","A"],
["now","tawa","توّة · also: taw","A"],
["man","rajel","راجل","N"],
["woman","mra","مرا","N"],
["child","tfol","طفل · also: sghir","N"],
["friend","sa7eb","صاحب · also: sa7bi = my friend","N"],
["mother","omm","أم · also: ommi, mama","N"],
["father","bou","بو · also: baba","N"],
["brother","khou","خو · also: khouya = my brother","N"],
["sister","okht","أخت · also: o5t","N"],
["family","3ayla","عايلة","N"],
["big","kbir","كبير","A"],
["small","sghir","صغير","A"],
["new","jdid","جديد","A"],
["old","9dim","قديم · also: kdim","A"],
["bad","khayeb","خايب · also: 5ayeb","A"],
["hot","skhoun","سخون · also: s5oun","A"],
["cold","bered","بارد","A"],
["expensive","ghali","غالي","A"],
["cheap","rkhis","رخيص · also: r5is","A"],
["quickly","fisa3","فيسع","A"],
["slowly","bchwaya","بشوية","A"],
["what?","chnowa","شنوة · also: chnia","B"],
["where?","win","وين","B"],
["who?","chkoun","شكون","B"],
["why?","3lech","علاش","B"],
["how?","kifech","كيفاش · also: kifach","B"],
["how much?","9addech","قدّاش · also: kaddech","B"],
["to go","nemchi","نمشي (I go) · mcha (he went)","V"],
["to come","nji","نجي (I come) · ja (he came)","V"],
["to eat","nekel","ناكل (I eat) · kla (he ate)","V"],
["to drink","nochrob","نشرب (I drink) · chrab (he drank)","V"],
["to see","nchouf","نشوف (I see) · chef (he saw)","V"],
["to speak","na7ki","نحكي (I speak) · 7ka (he spoke)","V"],
["to know","na3ref","نعرف (I know) · 3raf (he knew)","V"],
["to want / to love","n7eb","نحب (I want) · 7abb (he wanted)","V"],
["to work","nekhdem","نخدم (I work) · khdem (he worked)","V"],
["to sleep","nor9od","نرقد (I sleep) · r9ad (he slept)","V"],
["to buy","nechri","نشري (I buy) · chra (he bought)","V"],
["to give","na3ti","نعطي (I give) · a3tini = give me!","V"],
["to do / to make","na3mel","نعمل (I do) · 3mal (he did)","V"],
["to say","n9oul","نقول (I say) · 9al (he said)","V"],
["to go out","nokhroj","نخرج (I go out) · khraj (he went out)","V"],
["to understand","nefhem","نفهم (I understand) · fhem (he understood)","V"],
["good morning","sbe7 el khir","صباح الخير · also: sba7 el 5ir","B"],
["good evening","mse el khir","مساء الخير","B"],
["goodbye","beslema","بالسلامة · also: bislema","B"],
["how are you?","chnia 7welek?","شنية أحوالك · also: chna7welek","B"],
["I'm fine","labes","لاباس · also: labess","B"],
["God willing","inchallah","إن شاء الله · also: nchallah","B"],
["let's go!","yalla","يالله · also: haya","B"],
["one","we7ed","واحد","B"],
["two","zouz","زوز — Tunisian! not \"ithnan\"","B"],
["three","tletha","تلاثة","B"],
["five","khamsa","خمسة · also: 5amsa","B"],
["head","ras","راس","N"],
["hand","yed","يد","N"],
["eye","3in","عين","N"],
["heart","9alb","قلب · also: kalb","N"],
["sea","b7ar","بحر","N"],
["sun","chams","شمس","N"],
["problem","mochkla","مشكلة · also: mushkla","N"],
["sick","mridh","مريض","A"],
["tired","ta3ban","تعبان","A"],
["hungry","ji3an","جيعان","A"],
["thirsty","3atchan","عطشان","A"]
];
