// Vocabulaire Inférieur — the friend's original Greek deck (German → Greek), unchanged. cat: N noun, V verb, B basics.
window.TIER_NAMES = ["Ilote","Hoplite","Stratège","Philosophe"];
window.DECK = [
["Wasser","το νερό","to neró","N"],["Brot","το ψωμί","to psomí","N"],["Kaffee","ο καφές","o kafés","N"],
["Milch","το γάλα","to gála","N"],["Wein","το κρασί","to krasí","N"],["Bier","η μπίρα","i bíra","N"],
["Essen","το φαγητό","to fagitó","N"],["Haus","το σπίτι","to spíti","N"],["Straße","ο δρόμος","o drómos","N"],
["Stadt","η πόλη","i póli","N"],["Dorf","το χωριό","to chorió","N"],["Meer","η θάλασσα","i thálassa","N"],
["Strand","η παραλία","i paralía","N"],["Insel","το νησί","to nisí","N"],["Berg","το βουνό","to vounó","N"],
["Sonne","ο ήλιος","o ílios","N"],["Regen","η βροχή","i vrochí","N"],["Wind","ο αέρας","o aéras","N"],
["Tag","η μέρα","i méra","N"],["Nacht","η νύχτα","i níchta","N"],["Morgen (früh)","το πρωί","to proí","N"],
["Abend","το βράδυ","to vrádi","N"],["Woche","η εβδομάδα","i evdomáda","N"],["Monat","ο μήνας","o mínas","N"],
["Jahr","ο χρόνος","o chrónos","N"],["Uhrzeit / Stunde","η ώρα","i óra","N"],["Freund","ο φίλος","o fílos","N"],
["Freundin","η φίλη","i fíli","N"],["Frau","η γυναίκα","i gynaíka","N"],["Mann","ο άντρας","o ántras","N"],
["Kind","το παιδί","to pedí","N"],["Mutter","η μητέρα","i mitéra","N"],["Vater","ο πατέρας","o patéras","N"],
["Familie","η οικογένεια","i ikogénia","N"],["Name","το όνομα","to ónoma","N"],["Geld","τα λεφτά","ta leftá","N"],
["Arbeit","η δουλειά","i douliá","N"],["Schule","το σχολείο","to scholío","N"],["Buch","το βιβλίο","to vivlío","N"],
["Auto","το αυτοκίνητο","to aftokínito","N"],["Bus","το λεωφορείο","to leoforío","N"],["Flugzeug","το αεροπλάνο","to aeropláno","N"],
["Zug","το τρένο","to tréno","N"],["Fahrkarte","το εισιτήριο","to isitírio","N"],["Hotel","το ξενοδοχείο","to xenodochío","N"],
["Zimmer","το δωμάτιο","to domátio","N"],["Restaurant","το εστιατόριο","to estiatório","N"],["Rechnung","ο λογαριασμός","o logariasmós","N"],
["Speisekarte","ο κατάλογος","o katálogos","N"],["Laden","το μαγαζί","to magazí","N"],["Markt","η αγορά","i agorá","N"],
["Apotheke","το φαρμακείο","to farmakío","N"],["Arzt","ο γιατρός","o giatrós","N"],["Krankenhaus","το νοσοκομείο","to nosokomío","N"],
["Telefon","το τηλέφωνο","to tiléfono","N"],["Schlüssel","το κλειδί","to klidí","N"],["Tür","η πόρτα","i pórta","N"],
["Tisch","το τραπέζι","to trapézi","N"],["Stuhl","η καρέκλα","i karékla","N"],["Bett","το κρεβάτι","to kreváti","N"],
["Fenster","το παράθυρο","to paráthyro","N"],["Käse","το τυρί","to tyrí","N"],["Fleisch","το κρέας","to kréas","N"],
["Fisch","το ψάρι","to psári","N"],["Salat","η σαλάτα","i saláta","N"],["Obst","τα φρούτα","ta froúta","N"],
["Gemüse","τα λαχανικά","ta lachaniká","N"],["Zucker","η ζάχαρη","i záchari","N"],["Salz","το αλάτι","to aláti","N"],
["Öl","το λάδι","to ládi","N"],["Ei","το αυγό","to avgó","N"],["Suppe","η σούπα","i soúpa","N"],
["Nachtisch","το γλυκό","to glykó","N"],["Frage","η ερώτηση","i erótisi","N"],["Antwort","η απάντηση","i apántisi","N"],
["Wort","η λέξη","i léxi","N"],["Sprache","η γλώσσα","i glóssa","N"],["Hund","ο σκύλος","o skýlos","N"],
["Katze","η γάτα","i gáta","N"],["Kirche","η εκκλησία","i ekklisía","N"],["Platz","η πλατεία","i platía","N"],
["sein","είμαι","íme","V"],["haben","έχω","écho","V"],["machen","κάνω","káno","V"],
["gehen","πάω","páo","V"],["kommen","έρχομαι","érchome","V"],["sagen","λέω","léo","V"],
["sehen","βλέπω","vlépo","V"],["hören","ακούω","akoúo","V"],["essen","τρώω","tróo","V"],
["trinken","πίνω","píno","V"],["wissen","ξέρω","xéro","V"],["verstehen","καταλαβαίνω","katalavéno","V"],
["sprechen","μιλάω","miláo","V"],["wollen","θέλω","thélo","V"],["können","μπορώ","boró","V"],
["geben","δίνω","díno","V"],["nehmen","παίρνω","pérno","V"],["kaufen","αγοράζω","agorázo","V"],
["bezahlen","πληρώνω","pliróno","V"],["arbeiten","δουλεύω","doulévo","V"],["schlafen","κοιμάμαι","kimáme","V"],
["aufstehen","σηκώνομαι","sikónome","V"],["warten","περιμένω","periméno","V"],["suchen","ψάχνω","psáchno","V"],
["finden","βρίσκω","vrísko","V"],["öffnen","ανοίγω","anígo","V"],["schließen","κλείνω","klíno","V"],
["lieben","αγαπάω","agapáo","V"],["mir gefällt","μου αρέσει","mou arési","V"],["lernen","μαθαίνω","mathéno","V"],
["schreiben","γράφω","gráfo","V"],["lesen","διαβάζω","diavázo","V"],["helfen","βοηθάω","voitháo","V"],
["fahren (lenken)","οδηγώ","odigó","V"],["bleiben","μένω","méno","V"],["anfangen","αρχίζω","archízo","V"],
["beenden","τελειώνω","telióno","V"],["vergessen","ξεχνάω","xechnáo","V"],["sich erinnern","θυμάμαι","thymáme","V"],
["denken","σκέφτομαι","skéftome","V"],["glauben","πιστεύω","pistévo","V"],["brauchen","χρειάζομαι","chriázome","V"],
["spielen","παίζω","pézo","V"],["rennen","τρέχω","trécho","V"],["sitzen","κάθομαι","káthome","V"],
["stehen","στέκομαι","stékome","V"],["fragen","ρωτάω","rotáo","V"],["antworten","απαντάω","apantáo","V"],
["anrufen","τηλεφωνώ","tilefonó","V"],["kochen","μαγειρεύω","magirévo","V"],["gut","καλός","kalós","B"],
["schlecht","κακός","kakós","B"],["groß","μεγάλος","megálos","B"],["klein","μικρός","mikrós","B"],
["neu","καινούριος","kenoúrios","B"],["alt","παλιός","paliós","B"],["schön","ωραίος","oréos","B"],
["teuer","ακριβός","akrivós","B"],["billig","φτηνός","ftinós","B"],["schnell","γρήγορα","grígora","B"],
["langsam","σιγά","sigá","B"],["heute","σήμερα","símera","B"],["morgen","αύριο","ávrio","B"],
["gestern","χθες","chthes","B"],["jetzt","τώρα","tóra","B"],["immer","πάντα","pánta","B"],
["nie","ποτέ","poté","B"],["oft","συχνά","sychná","B"],["hier","εδώ","edó","B"],
["dort","εκεί","ekí","B"],["viel","πολύ","polý","B"],["wenig","λίγο","lígo","B"],
["ja","ναι","ne","B"],["nein","όχι","óchi","B"],["bitte","παρακαλώ","parakaló","B"],
["danke","ευχαριστώ","efcharistó","B"],["Entschuldigung","συγγνώμη","signómi","B"],["hallo","γεια σου","ya sou","B"],
["guten Morgen","καλημέρα","kaliméra","B"],["guten Abend","καλησπέρα","kalispéra","B"],["gute Nacht","καληνύχτα","kaliníchta","B"],
["auf Wiedersehen","αντίο","adío","B"],["wie geht es dir?","τι κάνεις;","ti kánis","B"],["wo?","πού;","pou","B"],
["wann?","πότε;","póte","B"],["warum?","γιατί;","yatí","B"],["wie?","πώς;","pos","B"],
["was?","τι;","ti","B"],["wer?","ποιος;","pios","B"],["wie viel?","πόσο;","póso","B"],
["und","και","ke","B"],["aber","αλλά","allá","B"],["weil","γιατί","yatí","B"],
["mit","με","me","B"],["ohne","χωρίς","chorís","B"],["für","για","ya","B"],
["auch","επίσης","epísis","B"],["vielleicht","ίσως","ísos","B"],["natürlich","βέβαια","vévea","B"],
["genug","αρκετά","arketá","B"],["Mensch","ο άνθρωπος","o ánthropos","N"],["Sache / Ding","το πράγμα","to prágma","N"],
["Zeit","ο καιρός","o kerós","N"],["Leben","η ζωή","i zoí","N"],["Welt","ο κόσμος","o kósmos","N"],
["Land","η χώρα","i chóra","N"],["Hand","το χέρι","to chéri","N"],["Auge","το μάτι","to máti","N"],
["Kopf","το κεφάλι","to kefáli","N"],["Herz","η καρδιά","i kardiá","N"],["Fuß / Bein","το πόδι","to pódi","N"],
["Körper","το σώμα","to sóma","N"],["Teil","το μέρος","to méros","N"],["Grund / Rede","ο λόγος","o lógos","N"],
["Art / Weise","ο τρόπος","o trópos","N"],["Fall","η περίπτωση","i períptosi","N"],["Problem","το πρόβλημα","to próvlima","N"],
["Idee","η ιδέα","i idéa","N"],["Meinung","η γνώμη","i gnómi","N"],["Wahrheit","η αλήθεια","i alíthia","N"],
["Kraft","η δύναμη","i dýnami","N"],["Nummer / Zahl","ο αριθμός","o arithmós","N"],["Preis","η τιμή","i timí","N"],
["Farbe","το χρώμα","to chróma","N"],["Musik","η μουσική","i mousikí","N"],["Film","η ταινία","i tenía","N"],
["Fest / Party","η γιορτή","i giortí","N"],["Geschenk","το δώρο","to dóro","N"],["Reise","το ταξίδι","to taxídi","N"],
["Weg / Straße","η οδός","i odós","N"],["Ecke","η γωνία","i gonía","N"],["Anfang","η αρχή","i archí","N"],
["Ende","το τέλος","to télos","N"],["Mitte","η μέση","i mési","N"],["Seite","η πλευρά","i plevrá","N"],
["Größe","το μέγεθος","to mégethos","N"],["Blatt / Zettel","το χαρτί","to chartí","N"],["Brief","το γράμμα","to grámma","N"],
["Zeitung","η εφημερίδα","i efimerída","N"],["Nachricht","το μήνυμα","to mínyma","N"],["Computer","ο υπολογιστής","o ypologistís","N"],
["Handy","το κινητό","to kinitó","N"],["Bank","η τράπεζα","i trápeza","N"],["Post","το ταχυδρομείο","to tachydromío","N"],
["Polizei","η αστυνομία","i astynomía","N"],["Flughafen","το αεροδρόμιο","to aerodrómio","N"],["Hafen","το λιμάνι","to limáni","N"],
["Bahnhof","ο σταθμός","o stathmós","N"],["Ausflug","η εκδρομή","i ekdromí","N"],["Wetter","ο καιρός","o kerós","N"],
["Schnee","το χιόνι","to chióni","N"],["Hitze","η ζέστη","i zésti","N"],["Kälte","το κρύο","to krýo","N"],
["Feuer","η φωτιά","i fotiá","N"],["Erde / Land","η γη","i gi","N"],["Himmel","ο ουρανός","o ouranós","N"],
["Baum","το δέντρο","to déntro","N"],["Blume","το λουλούδι","to louloúdi","N"],["Garten","ο κήπος","o kípos","N"],
["Tier","το ζώο","to zóo","N"],["Vogel","το πουλί","to poulí","N"],["Küche","η κουζίνα","i kouzína","N"],
["Bad","το μπάνιο","to bánio","N"],["Wohnung","το διαμέρισμα","to diamérisma","N"],["Etage / Boden","το πάτωμα","to pátoma","N"],
["Wand","ο τοίχος","o tíchos","N"],["Kleidung","τα ρούχα","ta roúcha","N"],["Schuh","το παπούτσι","to papoútsi","N"],
["Tasche","η τσάντα","i tsánta","N"],["Frühstück","το πρωινό","to proinó","N"],["Mittagessen","το μεσημεριανό","to mesimerianó","N"],
["Abendessen","το βραδινό","to vradinó","N"],["Glas","το ποτήρι","to potíri","N"],["Teller","το πιάτο","to piáto","N"],
["Löffel","το κουτάλι","to koutáli","N"],["Gabel","το πιρούνι","to piroúni","N"],["Messer","το μαχαίρι","to machéri","N"],
["Flasche","το μπουκάλι","to boukáli","N"],["Kartoffel","η πατάτα","i patáta","N"],["Tomate","η ντομάτα","i domáta","N"],
["Zwiebel","το κρεμμύδι","to kremmýdi","N"],["Apfel","το μήλο","to mílo","N"],["Orange","το πορτοκάλι","to portokáli","N"],
["Zitrone","το λεμόνι","to lemóni","N"],["Joghurt","το γιαούρτι","to giaoúrti","N"],["Honig","το μέλι","to méli","N"],
["Reis","το ρύζι","to rýzi","N"],["Kuchen","η τούρτα","i toúrta","N"],["Eis","το παγωτό","to pagotó","N"],
["Wasserflasche / Wasser mit Kohlensäure","το ανθρακούχο","to anthrakoúcho","N"],["schicken","στέλνω","stélno","V"],["bringen","φέρνω","férno","V"],
["setzen / stellen","βάζω","vázo","V"],["ziehen","τραβάω","traváo","V"],["zeigen","δείχνω","díchno","V"],
["erklären","εξηγώ","exigó","V"],["fragen (bitten)","ζητάω","zitáo","V"],["danken","ευχαριστώ","efcharistó","V"],
["gefallen (mögen)","συμπαθώ","sympathó","V"],["hoffen","ελπίζω","elpízo","V"],["fürchten","φοβάμαι","fováme","V"],
["lachen","γελάω","geláo","V"],["weinen","κλαίω","kléo","V"],["singen","τραγουδάω","tragoudáo","V"],
["tanzen","χορεύω","chorévo","V"],["reisen","ταξιδεύω","taxidévo","V"],["ankommen","φτάνω","ftáno","V"],
["weggehen","φεύγω","févgo","V"],["zurückkehren","γυρίζω","gyrízo","V"],["treffen","συναντάω","synantáo","V"],
["kennenlernen","γνωρίζω","gnorízo","V"],["ändern","αλλάζω","allázo","V"],["versuchen","προσπαθώ","prospathó","V"],
["gelingen","καταφέρνω","kataférno","V"],["wählen","διαλέγω","dialégo","V"],["entscheiden","αποφασίζω","apofasízo","V"],
["verlieren","χάνω","cháno","V"],["gewinnen","κερδίζω","kerdízo","V"],["benutzen","χρησιμοποιώ","chrisimopió","V"],
["putzen","καθαρίζω","katharízo","V"],["waschen","πλένω","pléno","V"],["kaputt machen","χαλάω","chaláo","V"],
["reparieren","φτιάχνω","ftiáchno","V"],["erlauben","επιτρέπω","epitrépo","V"],["müssen (es muss)","πρέπει","prépi","V"],
["kosten","κοστίζω","kostízo","V"],["glücklich","ευτυχισμένος","eftychisménos","B"],["traurig","λυπημένος","lypiménos","B"],
["müde","κουρασμένος","kourasménos","B"],["hungrig (ich habe Hunger)","πεινάω","peináo","B"],["durstig (ich habe Durst)","διψάω","dipsáo","B"],
["krank","άρρωστος","árrostos","B"],["gesund","υγιής","ygiís","B"],["einfach","εύκολος","éfkolos","B"],
["schwierig","δύσκολος","dýskolos","B"],["wichtig","σημαντικός","simantikós","B"],["möglich","δυνατός","dynatós","B"],
["voll","γεμάτος","gemátos","B"],["leer","άδειος","ádios","B"],["offen","ανοιχτός","anichtós","B"],
["geschlossen","κλειστός","klistós","B"],["warm","ζεστός","zestós","B"],["kalt","κρύος","krýos","B"],
["sauber","καθαρός","katharós","B"],["schmutzig","βρόμικος","vrómikos","B"],["lang","μακρύς","makrýs","B"],
["kurz","κοντός","kontós","B"],["hoch","ψηλός","psilós","B"],["niedrig","χαμηλός","chamilós","B"],
["jung","νέος","néos","B"],["ganz / alles","όλος","ólos","B"],["jeder","κάθε","káthe","B"],
["andere","άλλος","állos","B"],["gleich / selbe","ίδιος","ídios","B"],["zusammen","μαζί","mazí","B"],
["allein","μόνος","mónos","B"],["fast","σχεδόν","schedón","B"],["schon","ήδη","ídi","B"],
["noch","ακόμα","akóma","B"],["nur","μόνο","móno","B"],["sehr","πάρα πολύ","pára polý","B"],
["ein bisschen","λιγάκι","ligáki","B"],["vorher","πριν","prin","B"],["nachher","μετά","metá","B"],
["während","κατά τη διάρκεια","katá ti diárkia","B"],["zwischen","ανάμεσα","anámesa","B"],["über","πάνω","páno","B"],
["unter","κάτω","káto","B"],["vor (örtlich)","μπροστά","brostá","B"],["hinter","πίσω","píso","B"],
["neben","δίπλα","dípla","B"],["gegenüber","απέναντι","apénanti","B"],["drinnen","μέσα","mésa","B"],
["draußen","έξω","éxo","B"],["links","αριστερά","aristerá","B"],["rechts","δεξιά","dexiá","B"],
["geradeaus","ευθεία","efthía","B"],["wieder","ξανά","xaná","B"],["endlich","επιτέλους","epitélous","B"],
["sofort","αμέσως","amésos","B"],["langsam (Adv.)","αργά","argá","B"],["früh","νωρίς","norís","B"],
["spät","αργά το βράδυ","argá to vrádi","B"],["gerne","ευχαρίστως","efcharístos","B"],["kein Problem","κανένα πρόβλημα","kanéna próvlima","B"],
["Verzeihung (formell)","με συγχωρείτε","me synchoríte","B"]
];
// Cypriot Greek overrides: standard form (article stripped) -> [Cypriot form, pronunciation]
window.CYP = {"νερό":["νερόν","nerón"],"ψωμί":["ψωμίν","psomín"],"κρασί":["κρασίν","krasín"],"σπίτι":["σπίτιν","spítin"],"παιδί":["παιδίν","pedín"],"τυρί":["τυρίν","tirín"],"γάλα":["γάλαν","gálan"],"φαγητό":["φαΐν","faín"],"κρεβάτι":["καρκόλα","karkóla"],"καρέκλα":["τσαέρα","tsaéra"],"τραπέζι":["τραπέζιν","trapézin"],"ποτήρι":["ποτήριν","potírin"],"μαχαίρι":["μαχαίριν","machérin"],"κλειδί":["κλειδίν","klidín"],"νησί":["νησίν","nisín"],"χωριό":["χωρκόν","chorkón"],"τραγούδι":["τραούιν","traoúin"],"γάτα":["κάττα","kátta"],"σκύλος":["σιύλλος","shíllos"],"πουλί":["πουλλίν","poullín"],"λεφτά":["ριάλια","riália"],"χρήματα":["ριάλια","riália"],"αγόρι":["κοπελλούιν","kopelloúin"],"κορίτσι":["κορούα","koroúa"],"φίλος":["κουμπάρος","koumbáros"],"μωρό":["μωρόν","morón"],"αυτοκίνητο":["αμάξιν","amáxin"],"κάνω":["κάμνω","kámno"],"λέω":["λαλώ","laló"],"βλέπω":["θωρώ","thoró"],"μιλάω":["συντυχάννω","sindichánno"],"μιλώ":["συντυχάννω","sindichánno"],"δουλεύω":["δουλεύκω","douléfko"],"τώρα":["τωρά","torá"],"εδώ":["δαμέ","damé"],"εκεί":["τζιαμέ","djamé"],"πολύ":["πολλά","pollá"],"λίγο":["λλίο","llío"],"όχι":["όι","ói"],"και":["τζιαι","djé"],"τι":["ίντα","índa"],"τίποτα":["τίποτε","típote"],"χτες":["εχτές","echtés"],"χθες":["εχτές","echtés"],"πώς είσαι;":["ίντα κάμνεις;","índa kámnis"],"τι κάνεις;":["ίντα κάμνεις;","índa kámnis"],"τι κάνετε;":["ίντα κάμνετε;","índa kámnete"]};
