// Vocabulaire Inférieur — the friend's original Greek deck (German → Greek), unchanged. cat: N noun, V verb, B basics.
window.TIER_NAMES = ["Ilote","Hoplite","Stratège","Philosophe","Olympien"];
window.DECK = [
["Wasser","το νερό","to neró","N"],["Brot","το ψωμί","to psomí","N"],["Kaffee","ο καφές","o kafés","N"],
["Milch","το γάλα","to gála","N"],["Wein","το κρασί","to krasí","N"],["Bier","η μπίρα","i bíra","N"],
["Essen","το φαγητό","to fagitó","N"],["Haus","το σπίτι","to spíti","N"],["Straße","ο δρόμος","o drómos","N"],
["Stadt","η πόλη","i póli","N"],["Dorf","το χωριό","to chorió","N"],["Meer","η θάλασσα","i thálassa","N"],
["Strand","η παραλία","i paralía","N"],["Insel","το νησί","to nisí","N"],["Berg","το βουνό","to vounó","N"],
["Sonne","ο ήλιος","o ílios","N"],["Regen","η βροχή","i vrochí","N"],["Wind","ο αέρας","o aéras","N"],
["Tag","η μέρα","i méra","N"],["Nacht","η νύχτα","i níchta","N"],["Morgen (früh)","το πρωί","to proí","N"],
["Abend","το βράδυ","to vrádi","N"],["Woche","η εβδομάδα","i evdomáda","N"],["Monat","ο μήνας","o mínas","N"],
["Jahr","ο χρόνος","o chrónos","N"],["Uhrzeit / Stunde","η ώρα","i óra","N"],["Freund","ο φίλος","o fílos","N"],
["Freundin","η φίλη","i fíli","N"],["Frau","η γυναίκα","i gynaíka","N"],["Mann","ο άντρας","o ántras","N"],
["Kind","το παιδί","to pedí","N"],["Mutter","η μητέρα","i mitéra","N"],["Vater","ο πατέρας","o patéras","N"],
["Familie","η οικογένεια","i ikogénia","N"],["Name","το όνομα","to ónoma","N"],["Geld","τα λεφτά","ta leftá","N"],
["Arbeit","η δουλειά","i douliá","N"],["Schule","το σχολείο","to scholío","N"],["Buch","το βιβλίο","to vivlío","N"],
["Auto","το αυτοκίνητο","to aftokínito","N"],["Bus","το λεωφορείο","to leoforío","N"],["Flugzeug","το αεροπλάνο","to aeropláno","N"],
["Zug","το τρένο","to tréno","N"],["Fahrkarte","το εισιτήριο","to isitírio","N"],["Hotel","το ξενοδοχείο","to xenodochío","N"],
["Zimmer","το δωμάτιο","to domátio","N"],["Restaurant","το εστιατόριο","to estiatório","N"],["Rechnung","ο λογαριασμός","o logariasmós","N"],
["Speisekarte","ο κατάλογος","o katálogos","N"],["Laden","το μαγαζί","to magazí","N"],["Markt","η αγορά","i agorá","N"],
["Apotheke","το φαρμακείο","to farmakío","N"],["Arzt","ο γιατρός","o giatrós","N"],["Krankenhaus","το νοσοκομείο","to nosokomío","N"],
["Telefon","το τηλέφωνο","to tiléfono","N"],["Schlüssel","το κλειδί","to klidí","N"],["Tür","η πόρτα","i pórta","N"],
["Tisch","το τραπέζι","to trapézi","N"],["Stuhl","η καρέκλα","i karékla","N"],["Bett","το κρεβάτι","to kreváti","N"],
["Fenster","το παράθυρο","to paráthyro","N"],["Käse","το τυρί","to tyrí","N"],["Fleisch","το κρέας","to kréas","N"],
["Fisch","το ψάρι","to psári","N"],["Salat","η σαλάτα","i saláta","N"],["Obst","τα φρούτα","ta froúta","N"],
["Gemüse","τα λαχανικά","ta lachaniká","N"],["Zucker","η ζάχαρη","i záchari","N"],["Salz","το αλάτι","to aláti","N"],
["Öl","το λάδι","to ládi","N"],["Ei","το αυγό","to avgó","N"],["Suppe","η σούπα","i soúpa","N"],
["Nachtisch","το γλυκό","to glykó","N"],["Frage","η ερώτηση","i erótisi","N"],["Antwort","η απάντηση","i apántisi","N"],
["Wort","η λέξη","i léxi","N"],["Sprache","η γλώσσα","i glóssa","N"],["Hund","ο σκύλος","o skýlos","N"],
["Katze","η γάτα","i gáta","N"],["Kirche","η εκκλησία","i ekklisía","N"],["Platz","η πλατεία","i platía","N"],
["sein","είμαι","íme","V"],["haben","έχω","écho","V"],["machen","κάνω","káno","V"],
["gehen","πάω","páo","V"],["kommen","έρχομαι","érchome","V"],["sagen","λέω","léo","V"],
["sehen","βλέπω","vlépo","V"],["hören","ακούω","akoúo","V"],["essen","τρώω","tróo","V"],
["trinken","πίνω","píno","V"],["wissen","ξέρω","xéro","V"],["verstehen","καταλαβαίνω","katalavéno","V"],
["sprechen","μιλάω","miláo","V"],["wollen","θέλω","thélo","V"],["können","μπορώ","boró","V"],
["geben","δίνω","díno","V"],["nehmen","παίρνω","pérno","V"],["kaufen","αγοράζω","agorázo","V"],
["bezahlen","πληρώνω","pliróno","V"],["arbeiten","δουλεύω","doulévo","V"],["schlafen","κοιμάμαι","kimáme","V"],
["aufstehen","σηκώνομαι","sikónome","V"],["warten","περιμένω","periméno","V"],["suchen","ψάχνω","psáchno","V"],
["finden","βρίσκω","vrísko","V"],["öffnen","ανοίγω","anígo","V"],["schließen","κλείνω","klíno","V"],
["lieben","αγαπάω","agapáo","V"],["mir gefällt","μου αρέσει","mou arési","V"],["lernen","μαθαίνω","mathéno","V"],
["schreiben","γράφω","gráfo","V"],["lesen","διαβάζω","diavázo","V"],["helfen","βοηθάω","voitháo","V"],
["fahren (lenken)","οδηγώ","odigó","V"],["bleiben","μένω","méno","V"],["anfangen","αρχίζω","archízo","V"],
["beenden","τελειώνω","telióno","V"],["vergessen","ξεχνάω","xechnáo","V"],["sich erinnern","θυμάμαι","thymáme","V"],
["denken","σκέφτομαι","skéftome","V"],["glauben","πιστεύω","pistévo","V"],["brauchen","χρειάζομαι","chriázome","V"],
["spielen","παίζω","pézo","V"],["rennen","τρέχω","trécho","V"],["sitzen","κάθομαι","káthome","V"],
["stehen","στέκομαι","stékome","V"],["fragen","ρωτάω","rotáo","V"],["antworten","απαντάω","apantáo","V"],
["anrufen","τηλεφωνώ","tilefonó","V"],["kochen","μαγειρεύω","magirévo","V"],["gut","καλός","kalós","B"],
["schlecht","κακός","kakós","B"],["groß","μεγάλος","megálos","B"],["klein","μικρός","mikrós","B"],
["neu","καινούριος","kenoúrios","B"],["alt","παλιός","paliós","B"],["schön","ωραίος","oréos","B"],
["teuer","ακριβός","akrivós","B"],["billig","φτηνός","ftinós","B"],["schnell","γρήγορα","grígora","B"],
["langsam","σιγά","sigá","B"],["heute","σήμερα","símera","B"],["morgen","αύριο","ávrio","B"],
["gestern","χθες","chthes","B"],["jetzt","τώρα","tóra","B"],["immer","πάντα","pánta","B"],
["nie","ποτέ","poté","B"],["oft","συχνά","sychná","B"],["hier","εδώ","edó","B"],
["dort","εκεί","ekí","B"],["viel","πολύ","polý","B"],["wenig","λίγο","lígo","B"],
["ja","ναι","ne","B"],["nein","όχι","óchi","B"],["bitte","παρακαλώ","parakaló","B"],
["danke","ευχαριστώ","efcharistó","B"],["Entschuldigung","συγγνώμη","signómi","B"],["hallo","γεια σου","ya sou","B"],
["guten Morgen","καλημέρα","kaliméra","B"],["guten Abend","καλησπέρα","kalispéra","B"],["gute Nacht","καληνύχτα","kaliníchta","B"],
["auf Wiedersehen","αντίο","adío","B"],["wie geht es dir?","τι κάνεις;","ti kánis","B"],["wo?","πού;","pou","B"],
["wann?","πότε;","póte","B"],["warum?","γιατί;","yatí","B"],["wie?","πώς;","pos","B"],
["was?","τι;","ti","B"],["wer?","ποιος;","pios","B"],["wie viel?","πόσο;","póso","B"],
["und","και","ke","B"],["aber","αλλά","allá","B"],["weil","γιατί","yatí","B"],
["mit","με","me","B"],["ohne","χωρίς","chorís","B"],["für","για","ya","B"],
["auch","επίσης","epísis","B"],["vielleicht","ίσως","ísos","B"],["natürlich","βέβαια","vévea","B"],
["genug","αρκετά","arketá","B"],["Mensch","ο άνθρωπος","o ánthropos","N"],["Sache / Ding","το πράγμα","to prágma","N"],
["Zeit","ο καιρός","o kerós","N"],["Leben","η ζωή","i zoí","N"],["Welt","ο κόσμος","o kósmos","N"],
["Land","η χώρα","i chóra","N"],["Hand","το χέρι","to chéri","N"],["Auge","το μάτι","to máti","N"],
["Kopf","το κεφάλι","to kefáli","N"],["Herz","η καρδιά","i kardiá","N"],["Fuß / Bein","το πόδι","to pódi","N"],
["Körper","το σώμα","to sóma","N"],["Teil","το μέρος","to méros","N"],["Grund / Rede","ο λόγος","o lógos","N"],
["Art / Weise","ο τρόπος","o trópos","N"],["Fall","η περίπτωση","i períptosi","N"],["Problem","το πρόβλημα","to próvlima","N"],
["Idee","η ιδέα","i idéa","N"],["Meinung","η γνώμη","i gnómi","N"],["Wahrheit","η αλήθεια","i alíthia","N"],
["Kraft","η δύναμη","i dýnami","N"],["Nummer / Zahl","ο αριθμός","o arithmós","N"],["Preis","η τιμή","i timí","N"],
["Farbe","το χρώμα","to chróma","N"],["Musik","η μουσική","i mousikí","N"],["Film","η ταινία","i tenía","N"],
["Fest / Party","η γιορτή","i giortí","N"],["Geschenk","το δώρο","to dóro","N"],["Reise","το ταξίδι","to taxídi","N"],
["Weg / Straße","η οδός","i odós","N"],["Ecke","η γωνία","i gonía","N"],["Anfang","η αρχή","i archí","N"],
["Ende","το τέλος","to télos","N"],["Mitte","η μέση","i mési","N"],["Seite","η πλευρά","i plevrá","N"],
["Größe","το μέγεθος","to mégethos","N"],["Blatt / Zettel","το χαρτί","to chartí","N"],["Brief","το γράμμα","to grámma","N"],
["Zeitung","η εφημερίδα","i efimerída","N"],["Nachricht","το μήνυμα","to mínyma","N"],["Computer","ο υπολογιστής","o ypologistís","N"],
["Handy","το κινητό","to kinitó","N"],["Bank","η τράπεζα","i trápeza","N"],["Post","το ταχυδρομείο","to tachydromío","N"],
["Polizei","η αστυνομία","i astynomía","N"],["Flughafen","το αεροδρόμιο","to aerodrómio","N"],["Hafen","το λιμάνι","to limáni","N"],
["Bahnhof","ο σταθμός","o stathmós","N"],["Ausflug","η εκδρομή","i ekdromí","N"],["Wetter","ο καιρός","o kerós","N"],
["Schnee","το χιόνι","to chióni","N"],["Hitze","η ζέστη","i zésti","N"],["Kälte","το κρύο","to krýo","N"],
["Feuer","η φωτιά","i fotiá","N"],["Erde / Land","η γη","i gi","N"],["Himmel","ο ουρανός","o ouranós","N"],
["Baum","το δέντρο","to déntro","N"],["Blume","το λουλούδι","to louloúdi","N"],["Garten","ο κήπος","o kípos","N"],
["Tier","το ζώο","to zóo","N"],["Vogel","το πουλί","to poulí","N"],["Küche","η κουζίνα","i kouzína","N"],
["Bad","το μπάνιο","to bánio","N"],["Wohnung","το διαμέρισμα","to diamérisma","N"],["Etage / Boden","το πάτωμα","to pátoma","N"],
["Wand","ο τοίχος","o tíchos","N"],["Kleidung","τα ρούχα","ta roúcha","N"],["Schuh","το παπούτσι","to papoútsi","N"],
["Tasche","η τσάντα","i tsánta","N"],["Frühstück","το πρωινό","to proinó","N"],["Mittagessen","το μεσημεριανό","to mesimerianó","N"],
["Abendessen","το βραδινό","to vradinó","N"],["Glas","το ποτήρι","to potíri","N"],["Teller","το πιάτο","to piáto","N"],
["Löffel","το κουτάλι","to koutáli","N"],["Gabel","το πιρούνι","to piroúni","N"],["Messer","το μαχαίρι","to machéri","N"],
["Flasche","το μπουκάλι","to boukáli","N"],["Kartoffel","η πατάτα","i patáta","N"],["Tomate","η ντομάτα","i domáta","N"],
["Zwiebel","το κρεμμύδι","to kremmýdi","N"],["Apfel","το μήλο","to mílo","N"],["Orange","το πορτοκάλι","to portokáli","N"],
["Zitrone","το λεμόνι","to lemóni","N"],["Joghurt","το γιαούρτι","to giaoúrti","N"],["Honig","το μέλι","to méli","N"],
["Reis","το ρύζι","to rýzi","N"],["Kuchen","η τούρτα","i toúrta","N"],["Eis","το παγωτό","to pagotó","N"],
["Wasserflasche / Wasser mit Kohlensäure","το ανθρακούχο","to anthrakoúcho","N"],["schicken","στέλνω","stélno","V"],["bringen","φέρνω","férno","V"],
["setzen / stellen","βάζω","vázo","V"],["ziehen","τραβάω","traváo","V"],["zeigen","δείχνω","díchno","V"],
["erklären","εξηγώ","exigó","V"],["fragen (bitten)","ζητάω","zitáo","V"],["danken","ευχαριστώ","efcharistó","V"],
["gefallen (mögen)","συμπαθώ","sympathó","V"],["hoffen","ελπίζω","elpízo","V"],["fürchten","φοβάμαι","fováme","V"],
["lachen","γελάω","geláo","V"],["weinen","κλαίω","kléo","V"],["singen","τραγουδάω","tragoudáo","V"],
["tanzen","χορεύω","chorévo","V"],["reisen","ταξιδεύω","taxidévo","V"],["ankommen","φτάνω","ftáno","V"],
["weggehen","φεύγω","févgo","V"],["zurückkehren","γυρίζω","gyrízo","V"],["treffen","συναντάω","synantáo","V"],
["kennenlernen","γνωρίζω","gnorízo","V"],["ändern","αλλάζω","allázo","V"],["versuchen","προσπαθώ","prospathó","V"],
["gelingen","καταφέρνω","kataférno","V"],["wählen","διαλέγω","dialégo","V"],["entscheiden","αποφασίζω","apofasízo","V"],
["verlieren","χάνω","cháno","V"],["gewinnen","κερδίζω","kerdízo","V"],["benutzen","χρησιμοποιώ","chrisimopió","V"],
["putzen","καθαρίζω","katharízo","V"],["waschen","πλένω","pléno","V"],["kaputt machen","χαλάω","chaláo","V"],
["reparieren","φτιάχνω","ftiáchno","V"],["erlauben","επιτρέπω","epitrépo","V"],["müssen (es muss)","πρέπει","prépi","V"],
["kosten","κοστίζω","kostízo","V"],["glücklich","ευτυχισμένος","eftychisménos","B"],["traurig","λυπημένος","lypiménos","B"],
["müde","κουρασμένος","kourasménos","B"],["hungrig (ich habe Hunger)","πεινάω","peináo","B"],["durstig (ich habe Durst)","διψάω","dipsáo","B"],
["krank","άρρωστος","árrostos","B"],["gesund","υγιής","ygiís","B"],["einfach","εύκολος","éfkolos","B"],
["schwierig","δύσκολος","dýskolos","B"],["wichtig","σημαντικός","simantikós","B"],["möglich","δυνατός","dynatós","B"],
["voll","γεμάτος","gemátos","B"],["leer","άδειος","ádios","B"],["offen","ανοιχτός","anichtós","B"],
["geschlossen","κλειστός","klistós","B"],["warm","ζεστός","zestós","B"],["kalt","κρύος","krýos","B"],
["sauber","καθαρός","katharós","B"],["schmutzig","βρόμικος","vrómikos","B"],["lang","μακρύς","makrýs","B"],
["kurz","κοντός","kontós","B"],["hoch","ψηλός","psilós","B"],["niedrig","χαμηλός","chamilós","B"],
["jung","νέος","néos","B"],["ganz / alles","όλος","ólos","B"],["jeder","κάθε","káthe","B"],
["andere","άλλος","állos","B"],["gleich / selbe","ίδιος","ídios","B"],["zusammen","μαζί","mazí","B"],
["allein","μόνος","mónos","B"],["fast","σχεδόν","schedón","B"],["schon","ήδη","ídi","B"],
["noch","ακόμα","akóma","B"],["nur","μόνο","móno","B"],["sehr","πάρα πολύ","pára polý","B"],
["ein bisschen","λιγάκι","ligáki","B"],["vorher","πριν","prin","B"],["nachher","μετά","metá","B"],
["während","κατά τη διάρκεια","katá ti diárkia","B"],["zwischen","ανάμεσα","anámesa","B"],["über","πάνω","páno","B"],
["unter","κάτω","káto","B"],["vor (örtlich)","μπροστά","brostá","B"],["hinter","πίσω","píso","B"],
["neben","δίπλα","dípla","B"],["gegenüber","απέναντι","apénanti","B"],["drinnen","μέσα","mésa","B"],
["draußen","έξω","éxo","B"],["links","αριστερά","aristerá","B"],["rechts","δεξιά","dexiá","B"],
["geradeaus","ευθεία","efthía","B"],["wieder","ξανά","xaná","B"],["endlich","επιτέλους","epitélous","B"],
["sofort","αμέσως","amésos","B"],["langsam (Adv.)","αργά","argá","B"],["früh","νωρίς","norís","B"],
["spät","αργά το βράδυ","argá to vrádi","B"],["gerne","ευχαρίστως","efcharístos","B"],["kein Problem","κανένα πρόβλημα","kanéna próvlima","B"],
["Verzeihung (formell)","με συγχωρείτε","me synchoríte","B"],
// ── Tier 5 · Olympien — A2 Breite: Gefühle, Alltag, Konnektoren (expansion plan wave 1) ──
["Freude","η χαρά","i chará","N"],
["Angst","ο φόβος","o fóvos","N"],
["Liebe","η αγάπη","i agápi","N"],
["Traum","το όνειρο","to óniro","N"],
["Lüge","το ψέμα","to pséma","N"],
["Fehler","το λάθος","to láthos","N"],
["Ratschlag","η συμβουλή","i symvoulí","N"],
["Gefühl","το συναίσθημα","to synésthima","N"],
["Erinnerung","η ανάμνηση","i anámnisi","N"],
["Beispiel","το παράδειγμα","to parádigma","N"],
["Geschichte","η ιστορία","i istoría","N"],
["Ergebnis","το αποτέλεσμα","to apotélesma","N"],
["Möglichkeit","η δυνατότητα","i dynatótita","N"],
["Unterschied","η διαφορά","i diaforá","N"],
["Situation","η κατάσταση","i katástasi","N"],
["Moment / Augenblick","η στιγμή","i stigmí","N"],
["Wahl / Auswahl","η επιλογή","i epilogí","N"],
["Entscheidung","η απόφαση","i apófasi","N"],
["Gefahr","ο κίνδυνος","o kíndynos","N"],
["Frieden","η ειρήνη","i iríni","N"],
["Lärm","ο θόρυβος","o thóryvos","N"],
["Ruhe / Stille","η ησυχία","i isychía","N"],
["Glück (Chance)","η τύχη","i týchi","N"],
["Hoffnung","η ελπίδα","i elpída","N"],
["Trauer / Kummer","η λύπη","i lýpi","N"],
["Wut / Zorn","ο θυμός","o thymós","N"],
["Überraschung","η έκπληξη","i ékplixi","N"],
["Nachbar","ο γείτονας","o gítonas","N"],
["Gast / Besucher","ο επισκέπτης","o episképtis","N"],
["Fest / Feier","η γιορτή","i giortí","N"],
["Lied","το τραγούδι","to tragoúdi","N"],
["Spiel / Spielzeug","το παιχνίδι","to pechnídi","N"],
["Hilfe","η βοήθεια","i voíthia","N"],
["Beruf","το επάγγελμα","to epángelma","N"],
["Chef","το αφεντικό","to afentikó","N"],
["Kollege","ο συνάδελφος","o synádelfos","N"],
["Termin / Verabredung","το ραντεβού","to rantevoú","N"],
["Urlaub / Ferien","οι διακοπές","i diakopés","N"],
["Erde / Boden","η γη","i gi","N"],
["Licht","το φως","to fos","N"],
["Schatten","η σκιά","i skiá","N"],
["Stimme","η φωνή","i foní","N"],
["lächeln","χαμογελάω","chamogeláo","V"],
["fühlen","νιώθω","niótho","V"],
["werden","γίνομαι","gínome","V"],
["aufhören","σταματάω","stamatáo","V"],
["weitermachen","συνεχίζω","synechízo","V"],
["auswählen","διαλέγω","dialégo","V"],
["schaffen / erreichen","καταφέρνω","kataférno","V"],
["treffen (jemanden)","συναντάω","synantáo","V"],
["einladen","προσκαλώ","proskaló","V"],
["besuchen","επισκέπτομαι","episképtome","V"],
["bekommen / erhalten","λαμβάνω","lamváno","V"],
["tragen (schleppen)","κουβαλάω","kouvaláo","V"],
["folgen","ακολουθώ","akolouthó","V"],
["gewinnen / verdienen","κερδίζω","kerdízo","V"],
["zu Fuß gehen","περπατάω","perpatáo","V"],
["wirklich","πραγματικά","pragmatiká","B"],
["plötzlich","ξαφνικά","xafniká","B"],
["zuerst","πρώτα","próta","B"],
["danach","μετά","metá","B"],
["oder","ή","i","B"],
["wenn / falls","αν","an","B"],
["gegen","κατά","katá","B"],
["jeder / jede","κάθε","káthe","B"],
["etwas","κάτι","káti","B"],
["jemand","κάποιος","kápios","B"],
["niemand","κανείς","kanís","B"],
["nichts","τίποτα","típota","B"],
["überall","παντού","pantoú","B"],
["irgendwo","κάπου","kápou","B"],
["bald","σύντομα","sýntoma","B"],
// ── wave 2 · A2 → C1 Erweiterung (nur ANGEHÄNGT: bestehende Indizes und Fortschritts-Keys unverändert) ──
["Magen","το στομάχι","to stomáchi","N"],["Hals","ο λαιμός","o lemós","N"],["Nase","η μύτη","i míti","N"],
["Zahn","το δόντι","to dónti","N"],["Finger","το δάχτυλο","to dáchtylo","N"],["Haare","τα μαλλιά","ta malliá","N"],
["Gesicht","το πρόσωπο","to prósopo","N"],["Schulter","ο ώμος","o ómos","N"],["Knie","το γόνατο","to gónato","N"],
["Blut","το αίμα","to éma","N"],["Knochen","το κόκαλο","to kókalo","N"],["Haut","το δέρμα","to dérma","N"],
["Rücken","η πλάτη","i pláti","N"],["Gehirn","το μυαλό","to mialó","N"],["Brust","το στήθος","to stíthos","N"],
["Zunge","η γλώσσα (στόμα)","i glóssa","N"],["Fieber","ο πυρετός","o pyretós","N"],["Medikament","το φάρμακο","to fármako","N"],
["Behandlung","η θεραπεία","i therapía","N"],["Operation","η εγχείρηση","i enchírisi","N"],["Wunde","το τραύμα","to trávma","N"],
["Krankheit","η αρρώστια","i arróstia","N"],["Symptom","το σύμπτωμα","to sýmptoma","N"],["Krankenschwester","η νοσοκόμα","i nosokóma","N"],
["Versicherung","η ασφάλεια","i asfália","N"],["Diät","η δίαιτα","i díeta","N"],["Schlaf","ο ύπνος","o ýpnos","N"],
["Übung","η άσκηση","i áskisi","N"],["Stress","το άγχος","to ánchos","N"],["Gesundheit","η υγεία","i ygía","N"],
["Schmerz","ο πόνος","o pónos","N"],["Erholung","η ανάρρωση","i anárrosi","N"],["Zahnarzt","ο οδοντίατρος","o odontíatros","N"],
["Apotheker","ο φαρμακοποιός","o farmakopiós","N"],["Notfall","η επείγουσα ανάγκη","i epígousa anángi","N"],["Krankenwagen","το ασθενοφόρο","to asthenofóro","N"],
["Aufzug","το ασανσέρ","to asansér","N"],["Treppe","η σκάλα","i skála","N"],["Dach","η στέγη","i stégi","N"],
["Miete","το ενοίκιο","to eníkio","N"],["Gebäude","το κτίριο","to ktírio","N"],["Viertel (Stadtteil)","η γειτονιά","i gitoniá","N"],
["Brücke","η γέφυρα","i géfyra","N"],["Park","το πάρκο","to párko","N"],["Bürgersteig","το πεζοδρόμιο","to pezodrómio","N"],
["Verkehr","η κίνηση","i kínisi","N"],["Ampel","το φανάρι","to fanári","N"],["Parkplatz","το πάρκινγκ","to párking","N"],
["Fahrrad","το ποδήλατο","to podílato","N"],["Motorrad","η μοτοσικλέτα","i motosikléta","N"],["Taxi","το ταξί","to taxí","N"],
["U-Bahn","το μετρό","to metró","N"],["Fähre","το πλοίο","to plío","N"],["Gepäck","οι αποσκευές","i aposkevés","N"],
["Koffer","η βαλίτσα","i valítsa","N"],["Pass","το πασαπόρτο","to pasapórto","N"],["Grenze","τα σύνορα","ta sýnora","N"],
["Verspätung","η καθυστέρηση","i kathystérisi","N"],["Karte (Plan)","ο χάρτης","o chártis","N"],["Ausgang","η έξοδος","i éxodos","N"],
["Eingang","η είσοδος","i ísodos","N"],["Sturm","η καταιγίδα","i kategída","N"],["Wolke","το σύννεφο","to sýnnefo","N"],
["Nebel","η ομίχλη","i omíchli","N"],["Wald","το δάσος","to dásos","N"],["Fluss","το ποτάμι","to potámi","N"],
["See (Gewässer)","η λίμνη","i límni","N"],["Wüste","η έρημος","i érimos","N"],["Küste","η ακτή","i aktí","N"],
["Umwelt","το περιβάλλον","to perivállon","N"],["Verschmutzung","η μόλυνση","i mólynsi","N"],["Müll","τα σκουπίδια","ta skoupídia","N"],
["Energie","η ενέργεια","i enérgia","N"],["Strom","το ρεύμα","to révma","N"],["Klima","το κλίμα","to klíma","N"],
["Ernte","η σοδειά","i sodiá","N"],["Feld","το χωράφι","to choráfi","N"],["Art (Spezies)","το είδος","to ídos","N"],
["Natur","η φύση","i fýsi","N"],["Insekt","το έντομο","to éntomo","N"],["Fischer","ο ψαράς","o psarás","N"],
["Bauer","ο αγρότης","o agrótis","N"],["Lehrer","ο καθηγητής","o kathigitís","N"],["Schüler","ο μαθητής","o mathitís","N"],
["Student","ο φοιτητής","o fititís","N"],["Universität","το πανεπιστήμιο","to panepistímio","N"],["Prüfung","οι εξετάσεις","i exetásis","N"],
["Hausaufgabe","τα μαθήματα","ta mathímata","N"],["Note (Schule)","ο βαθμός","o vathmós","N"],["Klasse (Kurs)","η τάξη","i táxi","N"],
["Bibliothek","η βιβλιοθήκη","i vivliothíki","N"],["Wörterbuch","το λεξικό","to lexikó","N"],["Satz","η πρόταση","i prótasi","N"],
["Übersetzung","η μετάφραση","i metáfrasi","N"],["Aussprache","η προφορά","i proforá","N"],["Grammatik","η γραμματική","i grammatikí","N"],
["Bildschirm","η οθόνη","i othóni","N"],["Datei","το αρχείο","to archío","N"],["Passwort","ο κωδικός","o kodikós","N"],
["Internet","το διαδίκτυο","to diadíktyo","N"],["Netzwerk","το δίκτυο","to díktyo","N"],["Programm","το πρόγραμμα","to prógramma","N"],
["Daten","τα δεδομένα","ta dedoména","N"],["Gerät","η συσκευή","i syskeví","N"],["Anwendung / App","η εφαρμογή","i efarmogí","N"],
["Firma","η εταιρεία","i etería","N"],["Büro","το γραφείο","to grafío","N"],["Mitarbeiter","ο υπάλληλος","o ypállilos","N"],
["Arbeitgeber","ο εργοδότης","o ergodótis","N"],["Vertrag","το συμβόλαιο","to symvóleo","N"],["Gehalt","ο μισθός","o misthós","N"],
["Lohn (Bezahlung)","η πληρωμή","i pliromí","N"],["Rechnung (Faktura)","το τιμολόγιο","to timológio","N"],["Steuer","ο φόρος","o fóros","N"],
["Schulden","τα χρέη","ta chréi","N"],["Kredit","το δάνειο","to dánio","N"],["Konto","ο λογαριασμός (τράπεζα)","o logariasmós","N"],
["Gewinn","το κέρδος","to kérdos","N"],["Verlust","η ζημιά","i zimiá","N"],["Wirtschaft","η οικονομία","i ikonomía","N"],
["Industrie","η βιομηχανία","i viomichanía","N"],["Fabrik","το εργοστάσιο","to ergostásio","N"],["Arbeitslosigkeit","η ανεργία","i anergía","N"],
["Bewerbung","η αίτηση","i étisi","N"],["Vorstellungsgespräch","η συνέντευξη","i synénteyxi","N"],["Erfahrung","η εμπειρία","i empiría","N"],
["Ausbildung","η εκπαίδευση","i ekpédefsi","N"],["Fähigkeit","η ικανότητα","i ikanótita","N"],["Frist","η προθεσμία","i prothesmía","N"],
["Projekt","το έργο","to érgo","N"],["Team / Mannschaft","η ομάδα","i omáda","N"],["Bericht","η αναφορά","i anaforá","N"],
["Sitzung","η συνάντηση","i synántisi","N"],["Kunde","ο πελάτης","o pelátis","N"],["Lieferant","ο προμηθευτής","o promitheftís","N"],
["Angebot","η προσφορά","i prosforá","N"],["Nachfrage","η ζήτηση","i zítisi","N"],["Konkurrenz","ο ανταγωνισμός","o antagonismós","N"],
["Qualität","η ποιότητα","i piótita","N"],["Menge","η ποσότητα","i posótita","N"],["Rabatt","η έκπτωση","i ékptosi","N"],
["Quittung","η απόδειξη","i apódixi","N"],["Gesellschaft","η κοινωνία","i kinonía","N"],["Bürger","ο πολίτης","o polítis","N"],
["Regierung","η κυβέρνηση","i kyvérnisi","N"],["Wahl (Abstimmung)","οι εκλογές","i eklogés","N"],["Stimme (Wahl)","η ψήφος","i psífos","N"],
["Partei","το κόμμα","to kómma","N"],["Präsident","ο πρόεδρος","o próedros","N"],["Minister","ο υπουργός","o ypourgós","N"],
["Staat","το κράτος","to krátos","N"],["Macht","η εξουσία","i exousía","N"],["Recht (Anspruch)","το δικαίωμα","to dikéoma","N"],
["Pflicht","το καθήκον","to kathíkon","N"],["Freiheit","η ελευθερία","i elefthería","N"],["Gleichheit","η ισότητα","i isótita","N"],
["Gerechtigkeit","η δικαιοσύνη","i dikeosýni","N"],["Gesetz","ο νόμος","o nómos","N"],["Gericht","το δικαστήριο","to dikastírio","N"],
["Richter","ο δικαστής","o dikastís","N"],["Anwalt","ο δικηγόρος","o dikigóros","N"],["Verbrechen","το έγκλημα","to énklima","N"],
["Gefängnis","η φυλακή","i fylakí","N"],["Krieg","ο πόλεμος","o pólemos","N"],["Armee","ο στρατός","o stratós","N"],
["Sieg","η νίκη","i níki","N"],["Niederlage","η ήττα","i ítta","N"],["Grenze (Limit)","το όριο","to ório","N"],
["Bevölkerung","ο πληθυσμός","o plithysmós","N"],["Gemeinschaft","η κοινότητα","i kinótita","N"],["Generation","η γενιά","i geniá","N"],
["Armut","η φτώχεια","i ftóchia","N"],["Reichtum","ο πλούτος","o ploútos","N"],["Ungleichheit","η ανισότητα","i anisótita","N"],
["Migration","η μετανάστευση","i metanástefsi","N"],["Identität","η ταυτότητα","i taftótita","N"],["Kultur","ο πολιτισμός","o politismós","N"],
["Tradition","η παράδοση","i parádosi","N"],["Religion","η θρησκεία","i thriskía","N"],["Kunst","η τέχνη","i téchni","N"],
["Theater","το θέατρο","to théatro","N"],["Museum","το μουσείο","to musío","N"],["Jahrhundert","ο αιώνας","o eónas","N"],
["Zeitschrift","το περιοδικό","to periodikó","N"],["Artikel","το άρθρο","to árthro","N"],["Titel","ο τίτλος","o títlos","N"],
["Journalist","ο δημοσιογράφος","o dimosiográfos","N"],["Fernsehen","η τηλεόραση","i tileórasi","N"],["Radio","το ραδιόφωνο","to radiófono","N"],
["Werbung","η διαφήμιση","i diafímisi","N"],["Publikum","το κοινό","to kinó","N"],["Interview","η συνέντευξη (τύπου)","i synénteyxi","N"],
["Diskussion","η συζήτηση","i syzítisi","N"],["Beweis","η απόδειξη (τεκμήριο)","i apódixi","N"],["Quelle","η πηγή","i pigí","N"],
["Forschung","η έρευνα","i érevna","N"],["Studie","η μελέτη","i meléti","N"],["Zahl (Ziffer)","το νούμερο","to noúmero","N"],
["Prozent","το ποσοστό","to posostó","N"],["Durchschnitt","ο μέσος όρος","o mésos óros","N"],["Wachstum","η ανάπτυξη","i anáptyxi","N"],
["Gerücht","η φήμη","i fími","N"],["Skandal","το σκάνδαλο","to skándalo","N"],["Ruf (Reputation)","η υπόληψη","i ypólipsi","N"],
["Ursache","η αιτία","i etía","N"],["Folge","η συνέπεια","i synépia","N"],["Bedingung","η προϋπόθεση","i proipóthesi","N"],
["Schlussfolgerung","το συμπέρασμα","to sympérasma","N"],["Methode","η μέθοδος","i méthodos","N"],["Zweck / Ziel","ο σκοπός","o skopós","N"],
["Herausforderung","η πρόκληση","i próklisi","N"],["Vorteil","το πλεονέκτημα","to pleonéktima","N"],["Nachteil","το μειονέκτημα","to mionéktima","N"],
["Schwäche","η αδυναμία","i adynamía","N"],["Tendenz","η τάση","i tási","N"],["Wendepunkt","η καμπή","i kampí","N"],
["Widerspruch","η αντίφαση","i antífasi","N"],["Vorurteil","η προκατάληψη","i prokatálipsi","N"],["Kompromiss","ο συμβιβασμός","o symvivasmós","N"],
["Vereinbarung","η συμφωνία","i symfonía","N"],["Streit","η διαμάχη","i diamáchi","N"],["Verantwortung","η ευθύνη","i efthýni","N"],
["Regel","ο κανόνας","o kanónas","N"],["Vorschrift","ο κανονισμός","o kanonismós","N"],["Verfahren","η διαδικασία","i diadikasía","N"],
["Anforderung","η απαίτηση","i apétisi","N"],["Reform","η μεταρρύθμιση","i metarrýthmisi","N"],["Maßnahme","το μέτρο","to métro","N"],
["Politik (Konzept)","η πολιτική","i politikí","N"],["Haushalt (Budget)","ο προϋπολογισμός","o proipologismós","N"],["Finanzierung","η χρηματοδότηση","i chrimatodótisi","N"],
["Investition","η επένδυση","i epéndysi","N"],["Absicht","η πρόθεση","i próthesi","N"],["Bewusstsein","η συνείδηση","i synídisi","N"],
["Einstellung (Haltung)","η στάση","i stási","N"],["Charakter","ο χαρακτήρας","o charaktíras","N"],["Gewohnheit","η συνήθεια","i syníthia","N"],
["Verhalten","η συμπεριφορά","i symperiforá","N"],["Laune","η διάθεση","i diáthesi","N"],["Geduld","η υπομονή","i ypomoní","N"],
["Mut","το κουράγιο","to kourágio","N"],["Stolz","η περηφάνια","i perifánia","N"],["Scham","η ντροπή","i dropí","N"],
["Schuld (Verschulden)","η ενοχή","i enochí","N"],["Eifersucht","η ζήλια","i zília","N"],["Vertrauen","η εμπιστοσύνη","i empistosýni","N"],
["Zweifel","η αμφιβολία","i amfivolía","N"],["Neugier","η περιέργεια","i periérgia","N"],["Langeweile","η πλήξη","i plíxi","N"],
["Erleichterung","η ανακούφιση","i anakoúfisi","N"],["Bedauern","η μετάνοια","i metánia","N"],["Anstrengung","η προσπάθεια","i prospáthia","N"],
["Fortschritt","η πρόοδος","i próodos","N"],["Erfolg","η επιτυχία","i epitychía","N"],["Misserfolg","η αποτυχία","i apotychía","N"],
["zugeben","παραδέχομαι","paradéchome","V"],["leugnen","αρνούμαι","arnoúme","V"],["sich beschweren","διαμαρτύρομαι","diamartýrome","V"],
["sich entschuldigen","ζητάω συγγνώμη","zitáo signómi","V"],["warnen","προειδοποιώ","proidopió","V"],["drohen","απειλώ","apiló","V"],
["überzeugen","πείθω","pítho","V"],["verhandeln","διαπραγματεύομαι","diapragmatévome","V"],["streiten","μαλώνω","malóno","V"],
["lösen","λύνω","lýno","V"],["vermeiden","αποφεύγω","apofévgo","V"],["verringern","μειώνω","mióno","V"],
["erhöhen","αυξάνω","afxáno","V"],["ersetzen","αντικαθιστώ","antikathistó","V"],["abhängen von","εξαρτώμαι από","exartóme apó","V"],
["gehören","ανήκω","aníko","V"],["betreffen","αφορά","aforá","V"],["beeinflussen","επηρεάζω","epireázo","V"],
["erwarten","περιμένω (προσδοκώ)","periméno","V"],["annehmen (vermuten)","υποθέτω","ypothéto","V"],["zweifeln","αμφιβάλλω","amfivállo","V"],
["merken (bemerken)","παρατηρώ","paratiró","V"],["erkennen","αναγνωρίζω","anagnorízo","V"],["vergleichen","συγκρίνω","synkríno","V"],
["berücksichtigen","λαμβάνω υπόψη","lamváno ypópsi","V"],["beurteilen","κρίνω","kríno","V"],["kritisieren","επικρίνω","epikríno","V"],
["gratulieren","συγχαίρω","synchéro","V"],["ermutigen","ενθαρρύνω","entharrýno","V"],["unterstützen","υποστηρίζω","ypostirízo","V"],
["sich verlassen auf","βασίζομαι σε","vasízome se","V"],["vertrauen","εμπιστεύομαι","empistévome","V"],["aufgeben","παραιτούμαι","paretoúme","V"],
["beharren","επιμένω","epiméno","V"],["zögern","διστάζω","distázo","V"],["wagen","τολμάω","tolmáo","V"],
["riskieren","ρισκάρω","riskáro","V"],["sparen","αποταμιεύω","apotamiévo","V"],["ausgeben (Geld)","ξοδεύω","xodévo","V"],
["investieren","επενδύω","ependýo","V"],["einstellen (anheuern)","προσλαμβάνω","proslamváno","V"],["entlassen","απολύω","apolýo","V"],
["kündigen","παραιτούμαι από τη δουλειά","paretoúme apó ti douliá","V"],["sich bewerben","κάνω αίτηση","káno étisi","V"],["leiten","διοικώ","diikó","V"],
["gehorchen","υπακούω","ypakoúo","V"],["verbieten","απαγορεύω","apagorévo","V"],["erlauben (genehmigen)","εγκρίνω","enkríno","V"],
["ablehnen","απορρίπτω","aporrípto","V"],["verlangen","απαιτώ","apetó","V"],["gewähren","παραχωρώ","parachoró","V"],
["anvertrauen","εμπιστεύομαι κάτι","empistévome káti","V"],["beaufsichtigen","επιβλέπω","epivlépo","V"],["melden","αναφέρω","anaféro","V"],
["verbergen","κρύβω","krývo","V"],["beschuldigen","κατηγορώ","katigoró","V"],["beweisen","αποδεικνύω","apodiknýo","V"],
["widersprechen","αντιλέγω","antilégo","V"],["untergraben","υπονομεύω","yponomévo","V"],["überwinden","ξεπερνάω","xepernáo","V"],
["aushalten","αντέχω","antécho","V"],["nachgeben","υποχωρώ","ypochoró","V"],["widerstehen","αντιστέκομαι","antistékome","V"],
["sich verpflichten","δεσμεύομαι","desmévome","V"],["teilnehmen","συμμετέχω","symmetécho","V"],["beitragen","συμβάλλω","symvállo","V"],
["profitieren","επωφελούμαι","epofeloúme","V"],["ausnutzen","εκμεταλλεύομαι","ekmetallévome","V"],["wert sein","αξίζω","axízo","V"],
["betonen","τονίζω","tonízo","V"],["andeuten","υπονοώ","yponoó","V"],["behaupten","ισχυρίζομαι","ischyrízome","V"],
["klarstellen","ξεκαθαρίζω","xekatharízo","V"],["zusammenfassen","συνοψίζω","synopsízo","V"],["einschätzen","εκτιμώ","ektimó","V"],
["voraussehen","προβλέπω","provlépo","V"],["planen","σχεδιάζω","schediázo","V"],["durchführen","υλοποιώ","ylopió","V"],
["erreichen (Ziel)","επιτυγχάνω","epityncháno","V"],["übertreffen","υπερβαίνω","ypervéno","V"],["stärken","ενισχύω","enischýo","V"],
["schwächen","αδυνατίζω","adynatízo","V"],["bewahren","διατηρώ","diatiró","V"],["wiederherstellen","αποκαθιστώ","apokathistó","V"],
["anpassen","προσαρμόζω","prosarmózo","V"],["überdenken","επανεξετάζω","epanexetázo","V"],["verschieben","αναβάλλω","anavállo","V"],
["absagen","ακυρώνω","akyróno","V"],["bestätigen","επιβεβαιώνω","epivevaióno","V"],["übersetzen","μεταφράζω","metafrázo","V"],
["aussprechen","προφέρω","proféro","V"],["unterrichten","διδάσκω","didásko","V"],["scheinen (wirken)","φαίνομαι","fénome","V"],
["passieren","συμβαίνω","symvéno","V"],["prüfen","ελέγχω","eléncho","V"],["vorbereiten","προετοιμάζω","proetimázo","V"],
["organisieren","οργανώνω","organóno","V"],["mieten","νοικιάζω","nikiázo","V"],["verkaufen","πουλάω","pouláo","V"],
["liefern","παραδίδω","paradído","V"],["bestellen","παραγγέλνω","parangélno","V"],["wiegen","ζυγίζω","zygízo","V"],
["messen","μετράω","metráo","V"],["zählen","αριθμώ","arithmó","V"],["füllen","γεμίζω","gemízo","V"],
["leeren","αδειάζω","adiázo","V"],["schneiden","κόβω","kóvo","V"],["hinzufügen","προσθέτω","prosthéto","V"],
["entfernen","αφαιρώ","aferó","V"],["behalten","κρατάω","kratáo","V"],["werfen","πετάω","petáo","V"],
["fangen","πιάνω","piáno","V"],["berühren","αγγίζω","angízo","V"],["riechen","μυρίζω","myrízo","V"],
["probieren (kosten)","δοκιμάζω","dokimázo","V"],["sich ausruhen","ξεκουράζομαι","xekourázome","V"],["sich beeilen","βιάζομαι","viázome","V"],
["leihen (geben)","δανείζω","danízo","V"],["ausleihen (nehmen)","δανείζομαι","danízome","V"],["wiederholen","επαναλαμβάνω","epanalamváno","V"],
["verantwortlich","υπεύθυνος","ypéfthynos","B"],["zuverlässig","αξιόπιστος","axiópistos","B"],["ehrlich","ειλικρινής","ilikrinís","B"],
["großzügig","γενναιόδωρος","genneódoros","B"],["egoistisch","εγωιστής","egoistís","B"],["schüchtern","ντροπαλός","dropalós","B"],
["selbstsicher","σίγουρος","sígouros","B"],["ehrgeizig","φιλόδοξος","filódoxos","B"],["faul","τεμπέλης","tempélis","B"],
["fleißig","εργατικός","ergatikós","B"],["geduldig","υπομονετικός","ypomonetikós","B"],["ungeduldig","ανυπόμονος","anypómonos","B"],
["nervös","νευρικός","nevrikós","B"],["besorgt","ανήσυχος","anísychos","B"],["enttäuscht","απογοητευμένος","apogoitevménos","B"],
["zufrieden","ευχαριστημένος","efcharistiménos","B"],["dankbar","ευγνώμων","evgnómon","B"],["neugierig","περίεργος","periergos","B"],
["stur","πεισματάρης","pismatáris","B"],["klug","έξυπνος","éxypnos","B"],["freundlich","φιλικός","filikós","B"],
["böse (gemein)","κακός (μοχθηρός)","kakós","B"],["gesprächig","ομιλητικός","omilitikós","B"],["empfindlich","ευαίσθητος","evésthitos","B"],
["vernünftig","λογικός","logikós","B"],["gerecht","δίκαιος","díkeos","B"],["ungerecht","άδικος","ádikos","B"],
["notwendig","απαραίτητος","aparétitos","B"],["ausreichend","αρκετός","arketós","B"],["offensichtlich","φανερός","fanerós","B"],
["kompliziert","περίπλοκος","períplokos","B"],["einfach (schlicht)","απλός","aplós","B"],["häufig","συνηθισμένος","synithisménos","B"],
["selten","σπάνιος","spánios","B"],["neuerlich (kürzlich)","πρόσφατος","prósfatos","B"],["aktuell","τρέχων","tréchon","B"],
["modern","μοντέρνος","modérnos","B"],["örtlich","τοπικός","topikós","B"],["national","εθνικός","ethnikós","B"],
["ausländisch","ξένος","xénos","B"],["öffentlich","δημόσιος","dimósios","B"],["privat","ιδιωτικός","idiotikós","B"],
["verfügbar","διαθέσιμος","diathésimos","B"],["gründlich","διεξοδικός","diexodikós","B"],["genau","ακριβής","akrivís","B"],
["relevant","σχετικός","schetikós","B"],["bedeutend","σημαντικότερος","simantikóteros","B"],["unbedeutend","ασήμαντος","asímantos","B"],
["erheblich","αξιοσημείωτος","axiosimíotos","B"],["mäßig","μέτριος","métrios","B"],["übermäßig","υπερβολικός","ypervolikós","B"],
["zurückhaltend","διακριτικός","diakritikós","B"],["vorsichtig","προσεκτικός","prosektikós","B"],["unvorsichtig","απρόσεκτος","aprósektos","B"],
["absichtlich","σκόπιμος","skópimos","B"],["unerwartet","απροσδόκητος","aprosdókitos","B"],["unvermeidlich","αναπόφευκτος","anapófefktos","B"],
["nachhaltig","βιώσιμος","viósimos","B"],["schädlich","βλαβερός","vlaverós","B"],["nützlich","χρήσιμος","chrísimos","B"],
["unnütz","άχρηστος","áchristos","B"],["anspruchsvoll","απαιτητικός","apetitikós","B"],["mühsam","κοπιαστικός","kopiastikós","B"],
["zweideutig","διφορούμενος","diforoúmenos","B"],["irreführend","παραπλανητικός","paraplanitikós","B"],["überzeugend","πειστικός","pistikós","B"],
["ausgezeichnet","εξαιρετικός","exeretikós","B"],["mittelmäßig","μέτριος (κακός)","métrios","B"],["verbreitet","διαδεδομένος","diadedoménos","B"],
["bescheiden","μετριόφρων","metriófron","B"],["arrogant","αλαζόνας","alazónas","B"],["gleichgültig","αδιάφορος","adiáforos","B"],
["begeistert","ενθουσιασμένος","enthousiasménos","B"],["berühmt","διάσημος","diásimos","B"],["gefährlich","επικίνδυνος","epikíndynos","B"],
["sicher (gefahrlos)","ασφαλής","asfalís","B"],["stark","δυνατός (ισχυρός)","dynatós","B"],["schwach","αδύναμος","adýnamos","B"],
["schwer (Gewicht)","βαρύς","varýs","B"],["leicht (Gewicht)","ελαφρύς","elafrýs","B"],["tief","βαθύς","vathýs","B"],
["breit","φαρδύς","fardýs","B"],["eng","στενός","stenós","B"],["wahr","αληθινός","alithinós","B"],
["falsch","λάθος (ψεύτικος)","láthos","B"],["stolz","περήφανος","perífanos","B"],["höflich","ευγενικός","evgenikós","B"],
["unhöflich","αγενής","agenís","B"],["lustig","αστείος","astíos","B"],["ernst","σοβαρός","sovarós","B"],
["seltsam","παράξενος","paráxenos","B"],["obwohl","παρόλο που","parólo pou","B"],["sobald","μόλις","mólis","B"],
["bis (zeitlich)","μέχρι","méchri","B"],["solange","όσο","óso","B"],["damit","για να","ya na","B"],
["anstatt","αντί","antí","B"],["dank","χάρη σε","chári se","B"],["wegen","λόγω","lógo","B"],
["dagegen (andererseits)","αντίθετα","antítheta","B"],["außerdem","επιπλέον","epipléon","B"],["tatsächlich","πράγματι","prágmati","B"],
["kurz gesagt","με λίγα λόγια","me líga lógia","B"],["zum Beispiel","για παράδειγμα","ya parádigma","B"],["das heißt","δηλαδή","diladí","B"],
["vor allem","κυρίως","kyríos","B"],["mindestens","τουλάχιστον","touláchiston","B"],["höchstens","το πολύ","to polý","B"],
["übrigens","παρεμπιπτόντως","parempiptóntos","B"],["meiner Meinung nach","κατά τη γνώμη μου","katá ti gnómi mou","B"],["rechtzeitig","στην ώρα","stin óra","B"],
["wie üblich","ως συνήθως","os syníthos","B"],["nach und nach","σιγά σιγά","sigá sigá","B"],["von Zeit zu Zeit","πότε πότε","póte póte","B"],
["soweit ich weiß","απ' όσο ξέρω","ap' óso xéro","B"],["in Wirklichkeit","στην πραγματικότητα","stin pragmatikótita","B"],["alles in allem","συνολικά","synoliká","B"],
["allerdings","πάντως","pántos","B"],["im Gegenteil","αντιθέτως","antithétos","B"],["auf jeden Fall","σε κάθε περίπτωση","se káthe períptosi","B"],
["deshalb","γι' αυτό","gi' aftó","B"],["vorläufig","προς το παρόν","pros to parón","B"],["ab jetzt","από τώρα","apó tóra","B"],
["früher oder später","αργά ή γρήγορα","argá i grígora","B"],["absichtlich (Adv.)","επίτηδες","epítides","B"],["zufällig","τυχαία","tychéa","B"],
["auf den ersten Blick","με την πρώτη ματιά","me tin próti matiá","B"],["langfristig","μακροπρόθεσμα","makropróthesma","B"],["kurzfristig","βραχυπρόθεσμα","vrachypróthesma","B"],
["im Allgemeinen","γενικά","geniká","B"],["ungefähr","περίπου","perípou","B"],["genau (Adv.)","ακριβώς","akrivós","B"],
["kaum","μόλις και μετά βίας","mólis ke metá vías","B"],["kein Wunder","δεν είναι περίεργο","den íne periergo","B"],["es lohnt sich","αξίζει τον κόπο","axízi ton kópo","B"],
["es macht nichts","δεν πειράζει","den pirázi","B"],["um ehrlich zu sein","για να είμαι ειλικρινής","ya na íme ilikrinís","B"],["wie erwartet","όπως αναμενόταν","ópos anamenótan","B"],
["auf jeden Fall (sowieso)","έτσι κι αλλιώς","étsi ki alliós","B"],["Schritt für Schritt","βήμα βήμα","víma víma","B"],["bei näherem Nachdenken","αν το σκεφτείς καλύτερα","an to skeftís kalýtera","B"],
["Glückwunsch","συγχαρητήρια","syncharitíria","B"],["viel Erfolg","καλή επιτυχία","kalí epitychía","B"],["gute Reise","καλό ταξίδι","kaló taxídi","B"],
["herzlich willkommen","καλώς όρισες","kalós órises","B"],["zum Wohl","στην υγειά σου","stin ygiá sou","B"],["guten Appetit","καλή όρεξη","kalí órexi","B"],
["Vorsicht!","πρόσεχε!","prósexe","B"],["keine Sorge","μην ανησυχείς","min anisychís","B"],["ich bin einverstanden","συμφωνώ","symfonó","B"],
["ich bin anderer Meinung","διαφωνώ","diafonó","B"],["es hängt davon ab","εξαρτάται","exartáte","B"],["natürlich (selbstverständlich)","φυσικά","fysiká","B"]
];
// Cypriot Greek overrides: standard form (article stripped) -> [Cypriot form, pronunciation]
window.CYP = {"νερό":["νερόν","nerón"],"ψωμί":["ψωμίν","psomín"],"κρασί":["κρασίν","krasín"],"σπίτι":["σπίτιν","spítin"],"παιδί":["παιδίν","pedín"],"τυρί":["τυρίν","tirín"],"γάλα":["γάλαν","gálan"],"φαγητό":["φαΐν","faín"],"κρεβάτι":["καρκόλα","karkóla"],"καρέκλα":["τσαέρα","tsaéra"],"τραπέζι":["τραπέζιν","trapézin"],"ποτήρι":["ποτήριν","potírin"],"μαχαίρι":["μαχαίριν","machérin"],"κλειδί":["κλειδίν","klidín"],"νησί":["νησίν","nisín"],"χωριό":["χωρκόν","chorkón"],"τραγούδι":["τραούιν","traoúin"],"γάτα":["κάττα","kátta"],"σκύλος":["σιύλλος","shíllos"],"πουλί":["πουλλίν","poullín"],"λεφτά":["ριάλια","riália"],"χρήματα":["ριάλια","riália"],"αγόρι":["κοπελλούιν","kopelloúin"],"κορίτσι":["κορούα","koroúa"],"φίλος":["κουμπάρος","koumbáros"],"μωρό":["μωρόν","morón"],"αυτοκίνητο":["αμάξιν","amáxin"],"κάνω":["κάμνω","kámno"],"λέω":["λαλώ","laló"],"βλέπω":["θωρώ","thoró"],"μιλάω":["συντυχάννω","sindichánno"],"μιλώ":["συντυχάννω","sindichánno"],"δουλεύω":["δουλεύκω","douléfko"],"τώρα":["τωρά","torá"],"εδώ":["δαμέ","damé"],"εκεί":["τζιαμέ","djamé"],"πολύ":["πολλά","pollá"],"λίγο":["λλίο","llío"],"όχι":["όι","ói"],"και":["τζιαι","djé"],"τι":["ίντα","índa"],"τίποτα":["τίποτε","típote"],"χτες":["εχτές","echtés"],"χθες":["εχτές","echtés"],"πώς είσαι;":["ίντα κάμνεις;","índa kámnis"],"τι κάνεις;":["ίντα κάμνεις;","índa kámnis"],"τι κάνετε;":["ίντα κάμνετε;","índa kámnete"]};

// ── Cypriot coverage, wave 2 ─────────────────────────────────────────────────
// The 46 entries above are LEXICAL swaps (different word entirely). Most of the
// difference between standard and Cypriot Greek is regular, so the rest is
// derived from the deck at load time instead of being listed by hand:
//   1. neuter nouns keep their final -ν      το σπίτι  -> το σπίτιν
//   2. -εύω verbs become -εύκω               δουλεύω   -> δουλεύκω
//   3. deponents -ομαι/-άμαι -> -ουμαι/-ούμαι  κάθομαι -> κάθουμαι
// Lexical entries always win over a derived form.
window.CYP_RULES = true;
(function () {
  const LEX = {"όλος":["ούλλος","oúllos"],"όλα":["ούλλα","oúlla"],"μικρός":["μιτσής","mitsís"],"γυναίκα":["γεναίκα","genéka"],
    "ξέρω":["ηξέρω","ixéro"],"βρίσκω":["ευρίσκω","evrísko"],"σήμερα":["σήμμερα","símmera"],"αύριο":["αύριον","ávrion"],
    "γρήγορα":["γλήορα","glíora"],"μπορώ":["δύνουμαι","dýnoume"],"φοβάμαι":["φοούμαι","fooúme"],"κοιτάζω":["θωρώ","thoró"],
    "ψηλός":["ψιλός","psilós"],"έτοιμος":["έτοιμος","étimos"],"κοπέλα":["κοπέλλα","kopélla"],"ωραίος":["όμορφος","ómorfos"],
    "παππούς":["παππούς","pappoús"],"δουλειά":["δουλειά","douliá"],"σπίτι":["σπίτιν","spítin"]};
  const V = "αεηιουωάέήίόύώϊϋΐΰ";
  const ART = ["ο","η","το","οι","τα"];
  const CYP = window.CYP || {};
  const out = {};
  function bare(s) { const p = String(s).split(" "); return (["to","i","o","ta","tо"].indexOf(p[0]) >= 0 && p.length > 1) ? p.slice(1).join(" ") : String(s); }
  (window.DECK || []).forEach(function (w) {
    const parts = String(w[1]).split(" ");
    const art = ART.indexOf(parts[0]) >= 0 ? parts[0] : null;
    const base = art ? parts.slice(1).join(" ") : String(w[1]);
    const tr = bare(w[2]);
    if (!base || base.indexOf(" ") >= 0) return;            // single words only
    if (CYP[base] || out[base]) return;
    // 1 · neuter singular keeps final -ν
    if (art === "το" && V.indexOf(base.slice(-1)) >= 0) { out[base] = [base + "ν", tr + "n"]; return; }
    // 2 · -εύω / -εύομαι
    if (w[3] === "V" && base.slice(-3) === "εύω") { out[base] = [base.slice(0, -1) + "κω", tr.replace(/évo$/, "éfko")]; return; }
    if (w[3] === "V" && base.slice(-6) === "εύομαι") { out[base] = [base.slice(0, -5) + "κουμαι", tr.replace(/évome$/, "éfkoume")]; return; }
    // 3 · deponent endings
    if (w[3] === "V" && base.slice(-4) === "ομαι") { out[base] = [base.slice(0, -4) + "ουμαι", tr.replace(/ome$/, "oume")]; return; }
    if (w[3] === "V" && base.slice(-4) === "άμαι") { out[base] = [base.slice(0, -4) + "ούμαι", tr.replace(/áme$/, "oúme")]; return; }
  });
  window.CYP = Object.assign(out, CYP, LEX);
})();
