// NANI Work Mode — shared concept database (French + Tounsi), per NANI brief.
// Entry: [english, french, tounsi latin, tounsi arabic/display, cat, level, tnStatus]
// cat: N noun V verb A adj B phrase/chunk · level: 1 Survive, 2 Follow Production
// tnStatus: "l" likely (natural code-switch/common), "g" generated (needs native check)
// Tunisian forms deliberately keep French loanwords where the factory floor uses them.
window.NANI = [
// ── LEVEL 1 · SURVIVE ──
["the factory","l'usine","el usine","لوزين (Fr. loan)","N",1,"l"],
["the machine","la machine","el makina","الماكينة","N",1,"l"],
["the mould","le moule","el moule","المول (Fr. loan)","N",1,"l"],
["the production","la production","el production","البروديكسيون (Fr. loan)","N",1,"l"],
["the boss / manager","le chef","el chef","الشاف (Fr. loan)","N",1,"l"],
["the worker / operator","l'ouvrier","el khaddem","الخدّام","N",1,"l"],
["the colleague","le collègue","el collègue","الكولاڨ (Fr. loan)","N",1,"l"],
["the team","l'équipe","l'équipe","الإكيب (Fr. loan)","N",1,"l"],
["the meeting","la réunion","el réunion","الرينيون (Fr. loan)","N",1,"l"],
["work / job","le travail","el khedma","الخدمة","N",1,"l"],
["finished / done","terminé","wfet / kamel","وفات · كمل","A",1,"g"],
["not finished yet","pas encore terminé","mezel","مازال","A",1,"l"],
["today","aujourd'hui","lyoum","اليوم","A",1,"l"],
["tomorrow","demain","ghodwa","غدوة","A",1,"l"],
["now","maintenant","tawa","توة","A",1,"l"],
["later","plus tard","ba3d","بعد","A",1,"l"],
["quickly","vite","fisa3","فيسع","A",1,"l"],
["slowly / gently","doucement","bchwaya","بشوية","A",1,"l"],
["here","ici","houni","هوني","A",1,"l"],
["over there","là-bas","ghadi","غادي","A",1,"l"],
["good / OK","bien / d'accord","behi","باهي","A",1,"l"],
["not good","pas bon","mch behi","مش باهي","A",1,"l"],
["a problem","un problème","mochkla / problème","مشكلة","N",1,"l"],
["no problem","pas de problème","ma famech mochkla","ما فماش مشكلة","B",1,"g"],
["help me","aide-moi","3aweni","عاوني","V",1,"l"],
["show me","montre-moi","warrini","وريني","V",1,"l"],
["bring it","apporte-le","jib","جيب","V",1,"l"],
["take it / carry it","prends-le","hezz","هز","V",1,"l"],
["give me","donne-moi","a3tini","أعطيني","V",1,"l"],
["wait","attends","estanna","استنى","V",1,"l"],
["look","regarde","chouf","شوف","V",1,"l"],
["come","viens","ija","إيجا","V",1,"l"],
["go","va","emchi","امشي","V",1,"l"],
["put it aside","mets-le de côté","7ottou 3la jnab","حطو على جنب","B",1,"g"],
["how many pieces?","combien de pièces ?","9addech mel pièces?","قداش من پياس (code-switch)","B",1,"l"],
["the piece / part","la pièce","el pièce","الپياس (Fr. loan)","N",1,"l"],
["the quantity","la quantité","el quantité","الكونتيتي (Fr. loan)","N",1,"l"],
["the carton / box","le carton","el cartouna","الكرطونة","N",1,"l"],
["the colour","la couleur","el loun / couleur","اللون","N",1,"l"],
["the paint","la peinture","el bantoura","البنتورة (Fr. loan)","N",1,"l"],
["the sample","l'échantillon","l'échantillon","الشانتيون (Fr. loan)","N",1,"l"],
["the reference","la référence","la référence","الريفيرونس (Fr. loan)","N",1,"l"],
["the customer","le client","el client","الكليون (Fr. loan)","N",1,"l"],
["the quality","la qualité","la qualité","الكاليتي (Fr. loan)","N",1,"l"],
["broken / damaged","cassé / endommagé","mkasser","مكسر","A",1,"l"],
["it works","ça marche","temchi","تمشي","B",1,"l"],
["it doesn't work","ça ne marche pas","ma temchich","ما تمشيش","B",1,"l"],
["careful!","attention !","rod belek","رد بالك","B",1,"l"],
["where is…?","où est… ?","win…?","وين...؟","B",1,"l"],
["I don't understand","je ne comprends pas","ma fhemtech","ما فهمتش","B",1,"l"],
// ── LEVEL 2 · FOLLOW PRODUCTION ──
["the injection machine","la presse à injection","el presse","البراس (Fr. loan)","N",2,"g"],
["injection moulding","l'injection plastique","l'injection","الأنجيكسيون (Fr. loan)","N",2,"l"],
["the material","la matière","el matière","الماتيار (Fr. loan)","N",2,"l"],
["PVC","le PVC","PVC","بي ڥي سي","N",2,"l"],
["the pigment","le pigment","el pigment","البيڨمون (Fr. loan)","N",2,"g"],
["the machine is stopped","la machine est à l'arrêt","el makina m7absa","الماكينة محبوسة","B",2,"g"],
["start the machine","démarre la machine","démarri el makina","ديماري الماكينة (code-switch)","B",2,"g"],
["stop the machine","arrête la machine","7abbes el makina","حبس الماكينة","B",2,"g"],
["the mould is damaged","le moule est endommagé","el moule mkasser","المول مكسر","B",2,"l"],
["repair the mould","réparer le moule","sallah el moule","صلح المول","B",2,"l"],
["clean the mould","nettoyer le moule","naddhef el moule","نظف المول","B",2,"g"],
["the temperature","la température","la température","الطمبيراتير (Fr. loan)","N",2,"l"],
["too hot","trop chaud","skhoun barsha","سخون برشا","A",2,"l"],
["the cycle (machine)","le cycle","le cycle","السيكل (Fr. loan)","N",2,"g"],
["the defect","le défaut","el 3ib / défaut","العيب","N",2,"l"],
["deformed","déformé","déformé","ديفورمي (code-switch)","A",2,"g"],
["the flash (excess plastic)","la bavure","la bavure","الباڥير (Fr. loan)","N",2,"g"],
["the parting line","le plan de joint","le plan de joint","بلان دو جوان (technical Fr.)","N",2,"g"],
["approved / validated","validé","validé","ڥاليدي (Fr. loan)","A",2,"l"],
["rejected","refusé","refusé","روفيزي (Fr. loan)","A",2,"l"],
["redo it","refais-le","a3melha mel jdid","اعملها من جديد","B",2,"g"],
["the rework / retouch","la retouche","la retouche","الروتوش (Fr. loan)","N",2,"l"],
["compare with the reference","compare avec la référence","9aren mel référence","قارن مع الريفيرونس","B",2,"g"],
["too dark","trop foncé","ghami9 barsha","غامق برشا","A",2,"g"],
["too light","trop clair","fete7 barsha","فاتح برشا","A",2,"g"],
["paint is missing here","il manque de la peinture ici","fama bantoura na9sa houni","فما بنتورة ناقصة هوني","B",2,"g"],
["another layer (paint)","une autre couche","couche okhra","كوش أخرى (code-switch)","B",2,"g"],
["the airbrush","l'aérographe","el pistolet","البيستولي (Fr. loan)","N",2,"g"],
["the mask (painting)","le masque","el masque","الماسك (Fr. loan)","N",2,"l"],
["the assembly","l'assemblage","el montage","المونتاج (Fr. loan)","N",2,"l"],
["the glue","la colle","el colla","الكولة (Fr. loan)","N",2,"l"],
["the packaging","l'emballage","l'emballage","الأمبالاج (Fr. loan)","N",2,"l"],
["the label","l'étiquette","l'étiquette","الإتيكات (Fr. loan)","N",2,"l"],
["the warehouse","l'entrepôt / le magasin","el maghzen","المخزن","N",2,"l"],
["the stock","le stock","el stock","السطوك (Fr. loan)","N",2,"l"],
["the delivery","la livraison","la livraison","الليڥريزون (Fr. loan)","N",2,"l"],
["the deadline","le délai","le délai","الديلاي (Fr. loan)","N",2,"l"],
["urgent","urgent","mest3ajel / urgent","مستعجل","A",2,"l"],
["late / the delay","en retard / le retard","m'akher","متأخر","A",2,"l"],
["the order (production)","la commande","la commande","الكوموند (Fr. loan)","N",2,"l"],
["the planning / schedule","le planning","el planning","البلانينڨ (Fr. loan)","N",2,"l"],
["who is responsible?","qui est responsable ?","chkoun responsable?","شكون ريسبونسابل (code-switch)","B",2,"l"],
["what happened?","qu'est-ce qui s'est passé ?","chnowa sar?","شنوة صار؟","B",2,"l"],
["why is it late?","pourquoi c'est en retard ?","3lech m'akher?","علاش متأخر؟","B",2,"l"],
["when will it be finished?","quand est-ce que ce sera terminé ?","wa9tech youfa?","وقتاش يوفى؟","B",2,"g"],
["we need more material","il nous faut plus de matière","na7tajou matière akther","نحتاجو ماتيار أكثر","B",2,"g"],
["call maintenance","appelle la maintenance","3ayyet lel maintenance","عيط للمانتنونس (code-switch)","B",2,"g"],
["check 20 pieces","contrôle 20 pièces","controli 3echrin pièce","كونترولي عشرين پياس (code-switch)","B",2,"g"],
["it's acceptable","c'est acceptable","behi, ta3ddi","باهي، تعدّي","B",2,"g"],
["the client hasn't approved yet","le client n'a pas encore validé","el client mazel ma validech","الكليون مازال ما ڥاليداش","B",2,"g"]
];
// Adapter: builds an engine deck for one language from the shared DB.
window.NANI_DECK = function (lang) {
  return window.NANI.map(function (e) {
    if (lang === "fr") return [e[0], e[1], "NANI " + (e[5] === 1 ? "1 · Survive" : "2 · Production"), e[4]];
    var note = e[6] === "l" ? "" : " · à vérifier";
    return [e[0], e[2], e[3] + note, e[4]];
  });
};
