// Vocab War — canonical concept layer + world content.
// Each concept maps to the EXACT deck key per language (null = language lacks it).
// A tile is WAR-ACTIVE only when every faction has ALL its concepts — a missing
// key fogs the tile ("uncharted"), it NEVER shrinks a denominator.
// Greek deck keys are German (the friend's original deck).
window.WAR_CONTENT = {
  provinces: [
    { id: "coast", name: "People's Coast" },
    { id: "hearth", name: "Hearthlands" },
    { id: "chronos", name: "Chronos Reach" },
    { id: "market", name: "Market Kingdoms" },
    { id: "action", name: "Action Plains" },
    { id: "lexicon", name: "High Lexicon" },
    { id: "body", name: "Bodylands" },
    { id: "wild", name: "Wildlands" },
    { id: "workshop", name: "Workshop Belt" }
  ],
  concepts: {
    HELLO: { label: "hello", keys: { fr: "hello", el: "hallo", de: "hello", es: "hello", tn: "hello" } },
    THANKS: { label: "thank you", keys: { fr: "thank you", el: "danke", de: "thank you", es: "thank you", tn: "thank you" } },
    YES: { label: "yes", keys: { fr: "yes", el: "ja", de: "yes", es: "yes", tn: "yes" } },
    NO: { label: "no", keys: { fr: "no", el: "nein", de: "no", es: "no", tn: "no" } },
    PLEASE: { label: "please", keys: { fr: "please", el: "bitte", de: "please / you're welcome", es: "please", tn: "please" } },
    GOODBYE: { label: "goodbye", keys: { fr: "goodbye", el: "auf Wiedersehen", de: "goodbye", es: "goodbye", tn: "goodbye" } },
    HOWRU: { label: "how are you?", keys: { fr: "how are you?", el: "wie geht es dir?", de: "how are you?", es: "how are you?", tn: "how are you?" } },
    WHERE: { label: "where?", keys: { fr: "where?", el: "wo?", de: "where?", es: "where?", tn: "where?" } },
    WHAT: { label: "what?", keys: { fr: "what?", el: "was?", de: "what?", es: "what?", tn: "what?" } },
    WHO: { label: "who?", keys: { fr: "who?", el: "wer?", de: "who?", es: "who?", tn: "who?" } },
    WHY: { label: "why?", keys: { fr: "why?", el: "warum?", de: "why?", es: "why?", tn: "why?" } },
    HOW: { label: "how?", keys: { fr: "how?", el: "wie?", de: "how?", es: "how?", tn: "how?" } },
    MAN: { label: "man", keys: { fr: "man", el: "Mann", de: "man", es: "man", tn: "man" } },
    WOMAN: { label: "woman", keys: { fr: "woman", el: "Frau", de: "woman", es: "woman", tn: "woman" } },
    CHILD: { label: "child", keys: { fr: "child", el: "Kind", de: "child", es: "child", tn: "child" } },
    MOTHER: { label: "mother", keys: { fr: "mother", el: "Mutter", de: "mother", es: "mother", tn: "mother" } },
    FATHER: { label: "father", keys: { fr: "father", el: "Vater", de: "father", es: "father", tn: "father" } },
    FAMILY: { label: "family", keys: { fr: "family", el: "Familie", de: "family", es: "family", tn: "family" } },
    FRIEND: { label: "friend", keys: { fr: "friend", el: "Freund", de: "friend", es: "friend", tn: "friend" } },
    HOUSE: { label: "house", keys: { fr: "house", el: "Haus", de: "house", es: "house", tn: "house" } },
    DOOR: { label: "door", keys: { fr: "door", el: "Tür", de: "door", es: "door", tn: "door" } },
    KEY: { label: "key", keys: { fr: "key", el: "Schlüssel", de: "key", es: "key", tn: "key" } },
    CAR: { label: "car", keys: { fr: "car", el: "Auto", de: "car", es: "car", tn: "car" } },
    MONEY: { label: "money", keys: { fr: "money", el: "Geld", de: "money", es: "money", tn: "money" } },
    EXPENSIVE: { label: "expensive", keys: { fr: "expensive", el: "teuer", de: "expensive", es: "expensive", tn: "expensive" } },
    CHEAP: { label: "cheap", keys: { fr: "cheap", el: "billig", de: "cheap", es: "cheap", tn: "cheap" } },
    BUY: { label: "to buy", keys: { fr: "to buy", el: "kaufen", de: "to buy", es: "to buy", tn: "to buy" } },
    DAY: { label: "day", keys: { fr: "day", el: "Tag", de: "day", es: "day", tn: "day" } },
    NIGHT: { label: "night", keys: { fr: "night", el: "Nacht", de: "night", es: "night", tn: "night" } },
    TODAY: { label: "today", keys: { fr: "today", el: "heute", de: "today", es: "today", tn: "today" } },
    TOMORROW: { label: "tomorrow", keys: { fr: "tomorrow", el: "morgen", de: "tomorrow", es: "tomorrow", tn: "tomorrow" } },
    YESTERDAY: { label: "yesterday", keys: { fr: "yesterday", el: "gestern", de: "yesterday", es: "yesterday", tn: "yesterday" } },
    NOW: { label: "now", keys: { fr: "now", el: "jetzt", de: "now", es: "now", tn: "now" } },
    WATER: { label: "water", keys: { fr: "water", el: "Wasser", de: "water", es: "water", tn: "water" } },
    BREAD: { label: "bread", keys: { fr: "bread", el: "Brot", de: "bread", es: "bread", tn: "bread" } },
    MILK: { label: "milk", keys: { fr: "milk", el: "Milch", de: "milk", es: "milk", tn: "milk" } },
    COFFEE: { label: "coffee", keys: { fr: "coffee", el: "Kaffee", de: "coffee", es: "coffee", tn: "coffee" } },
    MEAT: { label: "meat", keys: { fr: "meat", el: "Fleisch", de: "meat", es: "meat", tn: "meat" } },
    GO: { label: "to go", keys: { fr: "to go", el: "gehen", de: "to go", es: "to go", tn: "to go" } },
    COME: { label: "to come", keys: { fr: "to come", el: "kommen", de: "to come", es: "to come", tn: "to come" } },
    EAT: { label: "to eat", keys: { fr: "to eat", el: "essen", de: "to eat", es: "to eat", tn: "to eat" } },
    DRINK: { label: "to drink", keys: { fr: "to drink", el: "trinken", de: "to drink", es: "to drink", tn: "to drink" } },
    SEE: { label: "to see", keys: { fr: "to see", el: "sehen", de: "to see", es: "to see", tn: "to see" } },
    SPEAK: { label: "to speak", keys: { fr: "to speak", el: "sprechen", de: "to speak", es: "to speak", tn: "to speak" } },
    KNOW: { label: "to know", keys: { fr: "to know (facts)", el: "wissen", de: "to know (a fact)", es: "to know (a fact)", tn: "to know" } },
    UNDERSTAND: { label: "to understand", keys: { fr: "to understand", el: "verstehen", de: "to understand", es: "to understand", tn: "to understand" } },
    SAY: { label: "to say", keys: { fr: "to say", el: "sagen", de: "to say", es: "to say", tn: "to say" } },
    MAKE: { label: "to do / make", keys: { fr: "to do / make", el: "machen", de: "to make / to do", es: "to do / to make", tn: "to do / to make" } },
    BIG: { label: "big", keys: { fr: "big", el: "groß", de: "big", es: "big", tn: "big" } },
    SMALL: { label: "small", keys: { fr: "small", el: "klein", de: "small", es: "small", tn: "small" } },
    NEW: { label: "new", keys: { fr: "new", el: "neu", de: "new", es: "new", tn: "new" } },
    OLD: { label: "old", keys: { fr: "old", el: "alt", de: "old", es: "old", tn: "old" } },
    GOOD: { label: "good", keys: { fr: "good", el: "gut", de: "good", es: "good", tn: "good / fine" } },
    BAD: { label: "bad", keys: { fr: "bad", el: "schlecht", de: "bad", es: "bad", tn: "bad" } },
    HAND: { label: "hand", keys: { fr: "hand", el: "Hand", de: "hand", es: "hand", tn: "hand" } },
    EYE: { label: "eye", keys: { fr: "eye", el: "Auge", de: "eye", es: "eye", tn: "eye" } },
    HEAD: { label: "head", keys: { fr: "head", el: "Kopf", de: "head", es: "head", tn: "head" } },
    SICK: { label: "sick", keys: { fr: "sick", el: "krank", de: "sick", es: "sick", tn: "sick" } },
    TIRED: { label: "tired", keys: { fr: "tired", el: "müde", de: "tired", es: "tired", tn: "tired" } },
    SUN: { label: "sun", keys: { fr: "sun", el: "Sonne", de: "sun", es: "sun", tn: "sun" } },
    SEA: { label: "sea", keys: { fr: "sea", el: "Meer", de: "sea", es: "sea", tn: "sea" } },
    HOT: { label: "hot", keys: { fr: "hot", el: "warm", de: "hot", es: "hot", tn: "hot" } },
    COLD: { label: "cold", keys: { fr: "cold", el: "kalt", de: "cold", es: "cold", tn: "cold" } },
    // fog-designed concepts (missing somewhere today — expansion events later)
    EGG: { label: "egg", keys: { fr: "egg", el: "Ei", de: "egg", es: "egg", tn: null } },
    CHEESE: { label: "cheese", keys: { fr: "cheese", el: "Käse", de: "cheese", es: "cheese", tn: null } },
    BUTTER: { label: "butter", keys: { fr: "butter", el: null, de: "butter", es: "butter", tn: null } },
    POTATO: { label: "potato", keys: { fr: "potato", el: null, de: "potato", es: "potato", tn: null } },
    COOK: { label: "to cook", keys: { fr: "to cook", el: "kochen", de: "to cook", es: "to cook", tn: null } },
    BOOK: { label: "book", keys: { fr: "book", el: "Buch", de: "book", es: "book", tn: null } },
    SCHOOL: { label: "school", keys: { fr: "school", el: "Schule", de: "school", es: "school", tn: null } },
    READ: { label: "to read", keys: { fr: "to read", el: "lesen", de: "to read", es: "to read", tn: null } },
    WRITE: { label: "to write", keys: { fr: "to write", el: "schreiben", de: "to write", es: "to write", tn: null } },
    LEARN: { label: "to learn", keys: { fr: "to learn", el: "lernen", de: "to learn", es: "to learn", tn: null } },
    DOCTOR: { label: "doctor", keys: { fr: "doctor", el: "Arzt", de: "doctor", es: "doctor", tn: null } },
    HOSPITAL: { label: "hospital", keys: { fr: "hospital", el: "Krankenhaus", de: "hospital", es: "hospital", tn: null } },
    PHARMACY: { label: "pharmacy", keys: { fr: "pharmacy", el: "Apotheke", de: "pharmacy", es: "pharmacy", tn: null } },
    HEALTHY: { label: "healthy", keys: { fr: null, el: "gesund", de: "healthy", es: "healthy", tn: null } },
    BIRD: { label: "bird", keys: { fr: "bird", el: null, de: "bird", es: "bird", tn: null } },
    FLY: { label: "to fly", keys: { fr: null, el: null, de: "to fly", es: "to fly", tn: null } },
    AIRPLANE: { label: "airplane", keys: { fr: "plane", el: "Flugzeug", de: "airplane", es: "airplane", tn: null } },
    TREE: { label: "tree", keys: { fr: "tree", el: null, de: "tree", es: "tree", tn: null } },
    WAR: { label: "war", keys: { fr: "war", el: null, de: "war", es: "war", tn: null } },
    WORD: { label: "word", keys: { fr: "word", el: "Wort", de: "word", es: "word", tn: null } },
    DICTIONARY: { label: "dictionary", keys: { fr: null, el: null, de: "dictionary", es: "dictionary", tn: null } },
    WORK_N: { label: "work", keys: { fr: "work", el: "Arbeit", de: "work", es: "work", tn: "work" } },
    WORK_V: { label: "to work", keys: { fr: "to work", el: "arbeiten", de: "to work", es: "to work", tn: "to work" } },
    MACHINE: { label: "machine", keys: { fr: null, el: null, de: null, es: null, tn: null } },
    FACTORY: { label: "factory", keys: { fr: null, el: null, de: null, es: null, tn: null } },
    PROBLEM: { label: "problem", keys: { fr: "problem", el: "Problem", de: null, es: null, tn: "problem" } }
  },
  // Geographic layout on the Europe/North-Africa map (viewBox 1020x573).
  // Homelands (home: langId) are faction capitals — always owned, never capturable.
  // Fantasy concept-territories sit between them; conquest spreads along "adj" edges.
  tiles: [
    { id: "h_fr", home: "fr", name: "France", x: 377, y: 275, r: 44, seed: 201, concepts: [] },
    { id: "h_es", home: "es", name: "España", x: 296, y: 367, r: 44, seed: 203, concepts: [] },
    { id: "h_de", home: "de", name: "Deutschland", x: 515, y: 229, r: 44, seed: 205, concepts: [] },
    { id: "h_el", home: "el", name: "Ελλάδα", x: 648, y: 381, r: 40, seed: 207, concepts: [] },
    { id: "h_tn", home: "tn", name: "Tounes", x: 505, y: 458, r: 40, seed: 209, concepts: [] },
    { id: "wings", province: "wild", name: "Wing Isles", x: 296, y: 128, r: 27, seed: 179, concepts: ["BIRD", "FLY", "AIRPLANE", "TREE"] },
    { id: "scale", province: "lexicon", name: "Scale Cliffs", x: 362, y: 158, r: 33, seed: 113, concepts: ["BIG", "SMALL", "NEW", "OLD", "GOOD", "BAD"] },
    { id: "days", province: "chronos", name: "Days Gate", x: 548, y: 146, r: 32, seed: 53, concepts: ["DAY", "NIGHT", "TODAY", "TOMORROW", "YESTERDAY", "NOW"] },
    { id: "scholar", province: "lexicon", name: "Scholar's Yard", x: 618, y: 70, r: 33, seed: 127, concepts: ["BOOK", "SCHOOL", "READ", "WRITE", "LEARN"] },
    { id: "hearth", province: "hearth", name: "Hearth Hall", x: 448, y: 192, r: 30, seed: 31, concepts: ["HOUSE", "DOOR", "KEY", "CAR"] },
    { id: "questions", province: "coast", name: "Question Crossroads", x: 336, y: 322, r: 29, seed: 23, concepts: ["WHERE", "WHAT", "WHO", "WHY", "HOW"] },
    { id: "greeting", province: "coast", name: "Greeting Harbor", x: 254, y: 402, r: 34, seed: 11, concepts: ["HELLO", "THANKS", "YES", "NO", "PLEASE", "GOODBYE", "HOWRU"] },
    { id: "family", province: "hearth", name: "Family Grove", x: 452, y: 300, r: 31, seed: 47, concepts: ["MAN", "WOMAN", "CHILD", "MOTHER", "FATHER", "FAMILY", "FRIEND"] },
    { id: "merchant", province: "market", name: "Merchant's Rest", x: 612, y: 258, r: 30, seed: 71, concepts: ["MONEY", "EXPENSIVE", "CHEAP", "BUY"] },
    { id: "mind", province: "action", name: "Mind Meadow", x: 688, y: 218, r: 33, seed: 103, concepts: ["KNOW", "UNDERSTAND", "SAY", "MAKE"] },
    { id: "verbs", province: "action", name: "Verb Fields", x: 630, y: 322, r: 34, seed: 97, concepts: ["GO", "COME", "EAT", "DRINK", "SEE", "SPEAK"] },
    { id: "breadbasket", province: "market", name: "Breadbasket Vale", x: 512, y: 334, r: 32, seed: 61, concepts: ["WATER", "BREAD", "MILK", "COFFEE", "MEAT"] },
    { id: "kitchen", province: "market", name: "Kitchen Court", x: 574, y: 400, r: 29, seed: 83, concepts: ["EGG", "CHEESE", "BUTTER", "POTATO", "COOK"] },
    { id: "bodykeep", province: "body", name: "Body Keep", x: 458, y: 380, r: 28, seed: 149, concepts: ["HAND", "EYE", "HEAD", "SICK", "TIRED"] },
    { id: "sunsea", province: "wild", name: "Sun & Sea", x: 366, y: 424, r: 27, seed: 167, concepts: ["SUN", "SEA", "HOT", "COLD"] },
    { id: "factory", province: "workshop", name: "Factory Gate", x: 380, y: 486, r: 38, seed: 191, concepts: ["WORK_N", "WORK_V", "MACHINE", "FACTORY", "PROBLEM"] },
    { id: "wardrum", province: "lexicon", name: "Wardrum Hills", x: 790, y: 350, r: 38, seed: 137, concepts: ["WAR", "WORD", "DICTIONARY"] },
    { id: "healer", province: "body", name: "Healer's Hollow", x: 748, y: 492, r: 38, seed: 157, concepts: ["DOCTOR", "HOSPITAL", "PHARMACY", "HEALTHY"] }
  ],
  // conquest spreads along these borders (undirected)
  adjacency: {
    h_fr: ["hearth", "questions", "family", "breadbasket", "scale"],
    h_es: ["greeting", "questions", "sunsea"],
    h_de: ["hearth", "days", "merchant", "family", "scholar"],
    h_el: ["verbs", "kitchen", "wardrum", "healer"],
    h_tn: ["factory", "kitchen", "bodykeep", "sunsea"],
    wings: ["scale"],
    scale: ["wings", "hearth", "days", "h_fr"],
    days: ["scale", "scholar", "h_de"],
    scholar: ["days", "h_de"],
    hearth: ["scale", "h_de", "h_fr"],
    questions: ["h_es", "h_fr", "sunsea", "greeting"],
    greeting: ["h_es", "questions"],
    family: ["h_fr", "h_de", "breadbasket", "merchant"],
    merchant: ["h_de", "mind", "verbs", "family"],
    mind: ["merchant", "verbs", "wardrum"],
    verbs: ["merchant", "h_el", "mind", "breadbasket"],
    breadbasket: ["family", "h_fr", "kitchen", "bodykeep", "verbs"],
    kitchen: ["breadbasket", "h_el", "h_tn"],
    bodykeep: ["breadbasket", "sunsea", "h_tn"],
    sunsea: ["h_es", "questions", "bodykeep", "h_tn"],
    factory: ["h_tn"],
    wardrum: ["h_el", "mind", "healer"],
    healer: ["wardrum", "h_el"]
  }
};
